import Test.Axioms
import Test.Semantics
import Test.Boundaries
import Test.LargeBoards
import Test.Bernstein
import Test.Gram
import Test.Stability
import Test.WeightedSweep
import Test.BlockFloor
import Test.CapacityEquality
import Test.RefinedSweep
import Test.SixMarginalBounds
import Test.SpectralSquare
import Test.SpectralSix
import Test.AlternatingSweep
import Test.SixMatrixBounds
import Test.SpectralSixMatrix
import Test.AlternatingSweepTen
import Test.OrderThree
import Test.BernsteinTransform
import Test.SpectralFour
import Test.FiveMarginalBounds
import Test.SpectralFiveGuards
import Test.OrderThreeSampling
import Test.OrderThreeLargeDimensions
import Test.SpectralFiveTensor
import Test.SpectralFiveBounds
import Test.OrderFourOrbit
import Test.OrderThreeLarge
import Test.SpectralFiveScalarBridges
import Test.BernsteinTensorRational
import Test.OrderThreeLargeFive
import Test.FiveCutAndScaling
import Test.OrderFour
import Test.ProductLoss
import Test.HomogeneousBlocks
import Test.FiveMinors
import Test.SpectralFiveSetup
import Test.SparsePolynomial
import Test.SpectralFiveSingletonPositive
import Test.SpectralFive
import Test.AllSquareOrders
import Test.ThreeRowKKT
import Test.ThreeRowSupportNormal
import Test.ThreeRowNoEmpty
import Test.ThreeRowGradient
import Test.ThreeRowLocal
import Test.ThreeRowPositive
import Test.ThreeRowProper
import Test.ElementarySymmetricBounds
import Test.RowProduct
import Test.ThreeRowTwoStar
import Test.ThreeRowSingletons
import Test.ThreeRowSingletonShape
import Test.ThreeRowGlobalSupport
import Test.ThreeRowSingleDoubletScalar
import Test.ThreeRowThreeDoublets
import Test.FourRowKernel
import Test.FourRowAveraging
import Test.FactorialDecay
import Test.ThreeRowSingleDoublet
import Test.ThreeRowTwoDoublets
import Test.ThreeRowFinal
import Test.EndpointContenders
import Test.FourRowConcentration
import Test.FourRowScalarGauge
