import Test.Axioms
import Test.Semantics
import Test.Boundaries
import Test.LargeBoards
import Test.Bernstein
import Test.Gram
import Test.Stability
import Test.WeightedSweep
import Test.BlockFloor
import Test.CapacityEquality
