import Test.Axioms
import Test.Semantics
import Test.Boundaries
import Test.LargeBoards
import Test.Bernstein
import Test.Gram
import Test.Stability
import Test.WeightedSweep
import Test.BlockFloor
import Test.CapacityEquality
import Test.RefinedSweep
import Test.SixMarginalBounds
import Test.SpectralSquare
import Test.SpectralSix
import Test.AlternatingSweep
import Test.SixMatrixBounds
import Test.SpectralSixMatrix
import Test.AlternatingSweepTen
import Test.OrderThree
import Test.BernsteinTransform
import Test.SpectralFour
import Test.FiveMarginalBounds
import Test.SpectralFiveGuards
import Test.OrderThreeSampling
import Test.OrderThreeLargeDimensions
import Test.SpectralFiveTensor
import Test.SpectralFiveBounds
import Test.OrderFourOrbit
