import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData50
import DR.Rectangular.FourRowFiniteData50Block11Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=50; multiplier seed 2; interaction sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite50Block11ActualPower (_i _j : Fin 1) : Fin 8 → ℚ :=
  fourRowFiniteInteractionPower 2 0 50
    (fun key => fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key))
    [(0,0),(0,0),(1,0)]

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite50Block11_power_actual : ∀ i j : Fin 1, ∀ d : Fin 10,
    fourRowFinite50Block11Power i j d = fourRowFinitePowerPad (fourRowFinite50Block11ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite50Block11_polynomial_actual (i j : Fin 1) :
    powerPolynomial (fourRowFinite50Block11Power i j) =
      fourRowFiniteInteractionPolynomial 2 0 50
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator50)
      [(0,0),(0,0),(1,0)] := by
  have he := funext (fourRowFinite50Block11_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteInteractionPower_polynomial 2 0 50 _ _

def fourRowFinite50Block11ActualEntry (u : ℝ) : Matrix (Fin 1) (Fin 1) ℝ := fun _i _j =>
  fourRowFiniteInteractionEntry 2 1
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,0),(1,0)]

theorem fourRowFinite50Block11_actualEntry_clear (u : ℝ) (_hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite50Block11Power i j k) u =
      fourRowFiniteDenominator 50 u • fourRowFinite50Block11ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite50Block11Power i j)) =
    fourRowFiniteDenominator 50 u*fourRowFinite50Block11ActualEntry u i j
  rw [fourRowFinite50Block11_polynomial_actual]
  rw [fourRowFiniteInteractionPolynomial_eval ]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite50Block11_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite50Block11ActualEntry u).PosDef := by
  have hp := fourRowFinite50Block11Polynomial_posDef u hu
  rw [fourRowFinite50Block11_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 50) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
