import DR.Rectangular.FourRowFiniteSeeds
import DR.Rectangular.FourRowFiniteData5Block0Physical
import DR.Rectangular.FourRowFiniteData5Block1Physical
import DR.Rectangular.FourRowFiniteData5Block2Physical
import DR.Rectangular.FourRowFiniteData5Block3Physical
import DR.Rectangular.FourRowFiniteData5Block4Physical
import DR.Rectangular.FourRowFiniteData5Block5Physical
import DR.Rectangular.FourRowFiniteData5Block6Physical
import DR.Rectangular.FourRowFiniteData5Block7Physical
import DR.Rectangular.FourRowFiniteData5Block8Physical
import DR.Rectangular.FourRowFiniteData5Block9Physical
import DR.Rectangular.FourRowFiniteData5Block10Physical
import DR.Rectangular.FourRowFiniteData5Block11Physical
import DR.Rectangular.FourRowFiniteData5Block12Physical
import DR.Rectangular.FourRowFiniteData5Block13Physical
import DR.Rectangular.FourRowFiniteData5Block14Physical
import DR.Rectangular.FourRowFiniteData5Block15Physical
import DR.Rectangular.FourRowFiniteData5Block16Physical
import DR.Rectangular.FourRowFiniteData5Block17Physical
import DR.Rectangular.FourRowFiniteData5Block18Physical
import DR.Rectangular.FourRowFiniteData5Block19Physical
import DR.Rectangular.FourRowFiniteData5Block20Physical
import DR.Rectangular.FourRowFiniteData5Block21Physical
import DR.Rectangular.FourRowFiniteData5Block22Physical
import DR.Rectangular.FourRowFiniteData5Block23Physical
import DR.Rectangular.FourRowFiniteData5Block24Physical
import DR.Rectangular.FourRowFiniteData5Block25Physical
import DR.Rectangular.FourRowFiniteData5Block26Physical
import DR.Rectangular.FourRowFiniteData5Block27Physical
import DR.Rectangular.FourRowFiniteData5Block28Physical
import DR.Rectangular.FourRowFiniteData5Block29Physical
import DR.Rectangular.FourRowFiniteData5Block30Physical
import DR.Rectangular.FourRowFiniteData5Block31Physical
import DR.Rectangular.FourRowFiniteData5Block32Physical
import DR.Rectangular.FourRowFiniteData5Block33Physical
import DR.Rectangular.FourRowFiniteData50Block0Physical
import DR.Rectangular.FourRowFiniteData50Block1Physical
import DR.Rectangular.FourRowFiniteData50Block2Physical
import DR.Rectangular.FourRowFiniteData50Block3Physical
import DR.Rectangular.FourRowFiniteData50Block4Physical
import DR.Rectangular.FourRowFiniteData50Block5Physical
import DR.Rectangular.FourRowFiniteData50Block6Physical
import DR.Rectangular.FourRowFiniteData50Block7Physical
import DR.Rectangular.FourRowFiniteData50Block8Physical
import DR.Rectangular.FourRowFiniteData50Block9Physical
import DR.Rectangular.FourRowFiniteData50Block10Physical
import DR.Rectangular.FourRowFiniteData50Block11Physical
import DR.Rectangular.FourRowFiniteData50Block12Physical
import DR.Rectangular.FourRowFiniteData50Block13Physical
import DR.Rectangular.FourRowFiniteData50Block14Physical
import DR.Rectangular.FourRowFiniteData50Block15Physical
import DR.Rectangular.FourRowFiniteData50Block16Physical
import DR.Rectangular.FourRowFiniteData50Block17Physical
import DR.Rectangular.FourRowFiniteData50Block18Physical
import DR.Rectangular.FourRowFiniteData50Block19Physical
import DR.Rectangular.FourRowFiniteData50Block20Physical
import DR.Rectangular.FourRowFiniteData50Block21Physical
import DR.Rectangular.FourRowFiniteData50Block22Physical
import DR.Rectangular.FourRowFiniteData50Block23Physical
import DR.Rectangular.FourRowFiniteData50Block24Physical
import DR.Rectangular.FourRowFiniteData50Block25Physical
import DR.Rectangular.FourRowFiniteData50Block26Physical
import DR.Rectangular.FourRowFiniteData50Block27Physical
import DR.Rectangular.FourRowFiniteData50Block28Physical
import DR.Rectangular.FourRowFiniteData50Block29Physical
import DR.Rectangular.FourRowFiniteData50Block30Physical
import DR.Rectangular.FourRowFiniteData50Block31Physical
import DR.Rectangular.FourRowFiniteData50Block32Physical
import DR.Rectangular.FourRowFiniteData50Block33Physical

/-! Generated by scripts/generate_four_row_finite_summary.py.
These interfaces refer to the actual ten seed matrices and all closed parameter
interval points. Coverage of arbitrary physical triples is a separate step. -/

namespace DittertRybin
noncomputable section

def fourRowFinite5RoleValue (u : ℝ) (key : ℕ) : ℝ :=
  fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key) u

theorem fourRowFinite5_trivial_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFiniteSeedTrivialMatrix s ((5 : ℝ)/u) (fourRowFinite5RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite5Block0ActualEntry u).PosDef
    exact fourRowFinite5Block0_actualEntry_posDef u hu
  · change (fourRowFinite5Block4ActualEntry u).PosDef
    exact fourRowFinite5Block4_actualEntry_posDef u hu
  · change (fourRowFinite5Block8ActualEntry u).PosDef
    exact fourRowFinite5Block8_actualEntry_posDef u hu
  · change (fourRowFinite5Block12ActualEntry u).PosDef
    exact fourRowFinite5Block12_actualEntry_posDef u hu
  · change (fourRowFinite5Block16ActualEntry u).PosDef
    exact fourRowFinite5Block16_actualEntry_posDef u hu
  · change (fourRowFinite5Block20ActualEntry u).PosDef
    exact fourRowFinite5Block20_actualEntry_posDef u hu
  · change (fourRowFinite5Block24ActualEntry u).PosDef
    exact fourRowFinite5Block24_actualEntry_posDef u hu
  · change (fourRowFinite5Block28ActualEntry u).PosDef
    exact fourRowFinite5Block28_actualEntry_posDef u hu
  · change (fourRowFinite5Block30ActualEntry u).PosDef
    exact fourRowFinite5Block30_actualEntry_posDef u hu
  · change (fourRowFinite5Block32ActualEntry u).PosDef
    exact fourRowFinite5Block32_actualEntry_posDef u hu

theorem fourRowFinite5_row_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1)
    (hr : fourRowFiniteSeedRows s < 3) :
    (fourRowFiniteSeedRowMatrix s ((5 : ℝ)/u) (fourRowFinite5RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite5Block1ActualEntry u).PosDef
    exact fourRowFinite5Block1_actualEntry_posDef u hu
  · change (fourRowFinite5Block5ActualEntry u).PosDef
    exact fourRowFinite5Block5_actualEntry_posDef u hu
  · change (fourRowFinite5Block9ActualEntry u).PosDef
    exact fourRowFinite5Block9_actualEntry_posDef u hu
  · change (fourRowFinite5Block13ActualEntry u).PosDef
    exact fourRowFinite5Block13_actualEntry_posDef u hu
  · change (fourRowFinite5Block17ActualEntry u).PosDef
    exact fourRowFinite5Block17_actualEntry_posDef u hu
  · change (fourRowFinite5Block21ActualEntry u).PosDef
    exact fourRowFinite5Block21_actualEntry_posDef u hu
  · change (fourRowFinite5Block25ActualEntry u).PosDef
    exact fourRowFinite5Block25_actualEntry_posDef u hu
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr

theorem fourRowFinite5_column_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFiniteSeedColumnMatrix s (fourRowFinite5RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite5Block2ActualEntry u).PosDef
    exact fourRowFinite5Block2_actualEntry_posDef u hu
  · change (fourRowFinite5Block6ActualEntry u).PosDef
    exact fourRowFinite5Block6_actualEntry_posDef u hu
  · change (fourRowFinite5Block10ActualEntry u).PosDef
    exact fourRowFinite5Block10_actualEntry_posDef u hu
  · change (fourRowFinite5Block14ActualEntry u).PosDef
    exact fourRowFinite5Block14_actualEntry_posDef u hu
  · change (fourRowFinite5Block18ActualEntry u).PosDef
    exact fourRowFinite5Block18_actualEntry_posDef u hu
  · change (fourRowFinite5Block22ActualEntry u).PosDef
    exact fourRowFinite5Block22_actualEntry_posDef u hu
  · change (fourRowFinite5Block26ActualEntry u).PosDef
    exact fourRowFinite5Block26_actualEntry_posDef u hu
  · change (fourRowFinite5Block29ActualEntry u).PosDef
    exact fourRowFinite5Block29_actualEntry_posDef u hu
  · change (fourRowFinite5Block31ActualEntry u).PosDef
    exact fourRowFinite5Block31_actualEntry_posDef u hu
  · change (fourRowFinite5Block33ActualEntry u).PosDef
    exact fourRowFinite5Block33_actualEntry_posDef u hu

theorem fourRowFinite5_interaction_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1)
    (hr : fourRowFiniteSeedRows s < 3) :
    (fourRowFiniteSeedInteractionMatrix s (fourRowFinite5RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite5Block3ActualEntry u).PosDef
    exact fourRowFinite5Block3_actualEntry_posDef u hu
  · change (fourRowFinite5Block7ActualEntry u).PosDef
    exact fourRowFinite5Block7_actualEntry_posDef u hu
  · change (fourRowFinite5Block11ActualEntry u).PosDef
    exact fourRowFinite5Block11_actualEntry_posDef u hu
  · change (fourRowFinite5Block15ActualEntry u).PosDef
    exact fourRowFinite5Block15_actualEntry_posDef u hu
  · change (fourRowFinite5Block19ActualEntry u).PosDef
    exact fourRowFinite5Block19_actualEntry_posDef u hu
  · change (fourRowFinite5Block23ActualEntry u).PosDef
    exact fourRowFinite5Block23_actualEntry_posDef u hu
  · change (fourRowFinite5Block27ActualEntry u).PosDef
    exact fourRowFinite5Block27_actualEntry_posDef u hu
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr

def fourRowFinite50RoleValue (u : ℝ) (key : ℕ) : ℝ :=
  fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key) u

theorem fourRowFinite50_trivial_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFiniteSeedTrivialMatrix s ((50 : ℝ)/u) (fourRowFinite50RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite50Block0ActualEntry u).PosDef
    exact fourRowFinite50Block0_actualEntry_posDef u hu
  · change (fourRowFinite50Block4ActualEntry u).PosDef
    exact fourRowFinite50Block4_actualEntry_posDef u hu
  · change (fourRowFinite50Block8ActualEntry u).PosDef
    exact fourRowFinite50Block8_actualEntry_posDef u hu
  · change (fourRowFinite50Block12ActualEntry u).PosDef
    exact fourRowFinite50Block12_actualEntry_posDef u hu
  · change (fourRowFinite50Block16ActualEntry u).PosDef
    exact fourRowFinite50Block16_actualEntry_posDef u hu
  · change (fourRowFinite50Block20ActualEntry u).PosDef
    exact fourRowFinite50Block20_actualEntry_posDef u hu
  · change (fourRowFinite50Block24ActualEntry u).PosDef
    exact fourRowFinite50Block24_actualEntry_posDef u hu
  · change (fourRowFinite50Block28ActualEntry u).PosDef
    exact fourRowFinite50Block28_actualEntry_posDef u hu
  · change (fourRowFinite50Block30ActualEntry u).PosDef
    exact fourRowFinite50Block30_actualEntry_posDef u hu
  · change (fourRowFinite50Block32ActualEntry u).PosDef
    exact fourRowFinite50Block32_actualEntry_posDef u hu

theorem fourRowFinite50_row_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1)
    (hr : fourRowFiniteSeedRows s < 3) :
    (fourRowFiniteSeedRowMatrix s ((50 : ℝ)/u) (fourRowFinite50RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite50Block1ActualEntry u).PosDef
    exact fourRowFinite50Block1_actualEntry_posDef u hu
  · change (fourRowFinite50Block5ActualEntry u).PosDef
    exact fourRowFinite50Block5_actualEntry_posDef u hu
  · change (fourRowFinite50Block9ActualEntry u).PosDef
    exact fourRowFinite50Block9_actualEntry_posDef u hu
  · change (fourRowFinite50Block13ActualEntry u).PosDef
    exact fourRowFinite50Block13_actualEntry_posDef u hu
  · change (fourRowFinite50Block17ActualEntry u).PosDef
    exact fourRowFinite50Block17_actualEntry_posDef u hu
  · change (fourRowFinite50Block21ActualEntry u).PosDef
    exact fourRowFinite50Block21_actualEntry_posDef u hu
  · change (fourRowFinite50Block25ActualEntry u).PosDef
    exact fourRowFinite50Block25_actualEntry_posDef u hu
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr

theorem fourRowFinite50_column_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFiniteSeedColumnMatrix s (fourRowFinite50RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite50Block2ActualEntry u).PosDef
    exact fourRowFinite50Block2_actualEntry_posDef u hu
  · change (fourRowFinite50Block6ActualEntry u).PosDef
    exact fourRowFinite50Block6_actualEntry_posDef u hu
  · change (fourRowFinite50Block10ActualEntry u).PosDef
    exact fourRowFinite50Block10_actualEntry_posDef u hu
  · change (fourRowFinite50Block14ActualEntry u).PosDef
    exact fourRowFinite50Block14_actualEntry_posDef u hu
  · change (fourRowFinite50Block18ActualEntry u).PosDef
    exact fourRowFinite50Block18_actualEntry_posDef u hu
  · change (fourRowFinite50Block22ActualEntry u).PosDef
    exact fourRowFinite50Block22_actualEntry_posDef u hu
  · change (fourRowFinite50Block26ActualEntry u).PosDef
    exact fourRowFinite50Block26_actualEntry_posDef u hu
  · change (fourRowFinite50Block29ActualEntry u).PosDef
    exact fourRowFinite50Block29_actualEntry_posDef u hu
  · change (fourRowFinite50Block31ActualEntry u).PosDef
    exact fourRowFinite50Block31_actualEntry_posDef u hu
  · change (fourRowFinite50Block33ActualEntry u).PosDef
    exact fourRowFinite50Block33_actualEntry_posDef u hu

theorem fourRowFinite50_interaction_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1)
    (hr : fourRowFiniteSeedRows s < 3) :
    (fourRowFiniteSeedInteractionMatrix s (fourRowFinite50RoleValue u)).PosDef := by
  fin_cases s
  · change (fourRowFinite50Block3ActualEntry u).PosDef
    exact fourRowFinite50Block3_actualEntry_posDef u hu
  · change (fourRowFinite50Block7ActualEntry u).PosDef
    exact fourRowFinite50Block7_actualEntry_posDef u hu
  · change (fourRowFinite50Block11ActualEntry u).PosDef
    exact fourRowFinite50Block11_actualEntry_posDef u hu
  · change (fourRowFinite50Block15ActualEntry u).PosDef
    exact fourRowFinite50Block15_actualEntry_posDef u hu
  · change (fourRowFinite50Block19ActualEntry u).PosDef
    exact fourRowFinite50Block19_actualEntry_posDef u hu
  · change (fourRowFinite50Block23ActualEntry u).PosDef
    exact fourRowFinite50Block23_actualEntry_posDef u hu
  · change (fourRowFinite50Block27ActualEntry u).PosDef
    exact fourRowFinite50Block27_actualEntry_posDef u hu
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr
  · norm_num [fourRowFiniteSeedRows] at hr

end
end DittertRybin
