import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData5
import DR.Rectangular.FourRowFiniteData5Block32Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=5; multiplier seed 9; trivial sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite5Block32ActualPower (i j : Fin 15) : Fin 8 → ℚ :=
  fourRowFiniteTrivialPower 3 2 5
    (fun key => fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key))
    [(0,0),(1,1),(2,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite5Block32_power_actual : ∀ i j : Fin 15, ∀ d : Fin 10,
    fourRowFinite5Block32Power i j d = fourRowFinitePowerPad (fourRowFinite5Block32ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite5Block32_polynomial_actual (i j : Fin 15) :
    powerPolynomial (fourRowFinite5Block32Power i j) =
      fourRowFiniteTrivialPolynomial 3 2 5
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator5)
      [(0,0),(1,1),(2,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4)) := by
  have he := funext (fourRowFinite5Block32_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteTrivialPower_polynomial 3 2 5 _ _ ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

def fourRowFinite5Block32ActualEntry (u : ℝ) : Matrix (Fin 15) (Fin 15) ℝ := fun i j =>
  fourRowFiniteTrivialEntry 3 3 ((5 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key) u)
    [(0,0),(1,1),(2,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

theorem fourRowFinite5Block32_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite5Block32Power i j k) u =
      fourRowFiniteDenominator 5 u • fourRowFinite5Block32ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite5Block32Power i j)) =
    fourRowFiniteDenominator 5 u*fourRowFinite5Block32ActualEntry u i j
  rw [fourRowFinite5Block32_polynomial_actual]
  rw [fourRowFiniteTrivialPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite5Block32_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite5Block32ActualEntry u).PosDef := by
  have hp := fourRowFinite5Block32Polynomial_posDef u hu
  rw [fourRowFinite5Block32_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 5) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
