import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData5
import DR.Rectangular.FourRowFiniteData5Block16Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=5; multiplier seed 4; trivial sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite5Block16ActualPower (i j : Fin 7) : Fin 8 → ℚ :=
  fourRowFiniteTrivialPower 1 2 5
    (fun key => fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key))
    [(0,0),(0,1),(0,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite5Block16_power_actual : ∀ i j : Fin 7, ∀ d : Fin 10,
    fourRowFinite5Block16Power i j d = fourRowFinitePowerPad (fourRowFinite5Block16ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite5Block16_polynomial_actual (i j : Fin 7) :
    powerPolynomial (fourRowFinite5Block16Power i j) =
      fourRowFiniteTrivialPolynomial 1 2 5
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator5)
      [(0,0),(0,1),(0,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4)) := by
  have he := funext (fourRowFinite5Block16_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteTrivialPower_polynomial 1 2 5 _ _ ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

def fourRowFinite5Block16ActualEntry (u : ℝ) : Matrix (Fin 7) (Fin 7) ℝ := fun i j =>
  fourRowFiniteTrivialEntry 1 3 ((5 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,1),(0,2)] ((i.val/4),(i.val%4)) ((j.val/4),(j.val%4))

theorem fourRowFinite5Block16_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite5Block16Power i j k) u =
      fourRowFiniteDenominator 5 u • fourRowFinite5Block16ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite5Block16Power i j)) =
    fourRowFiniteDenominator 5 u*fourRowFinite5Block16ActualEntry u i j
  rw [fourRowFinite5Block16_polynomial_actual]
  rw [fourRowFiniteTrivialPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite5Block16_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite5Block16ActualEntry u).PosDef := by
  have hp := fourRowFinite5Block16Polynomial_posDef u hu
  rw [fourRowFinite5Block16_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 5) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
