import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData5
import DR.Rectangular.FourRowFiniteData5Block4Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=5; multiplier seed 1; trivial sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite5Block4ActualPower (i j : Fin 5) : Fin 8 → ℚ :=
  fourRowFiniteTrivialPower 1 1 5
    (fun key => fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key))
    [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite5Block4_power_actual : ∀ i j : Fin 5, ∀ d : Fin 10,
    fourRowFinite5Block4Power i j d = fourRowFinitePowerPad (fourRowFinite5Block4ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite5Block4_polynomial_actual (i j : Fin 5) :
    powerPolynomial (fourRowFinite5Block4Power i j) =
      fourRowFiniteTrivialPolynomial 1 1 5
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator5)
      [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3)) := by
  have he := funext (fourRowFinite5Block4_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteTrivialPower_polynomial 1 1 5 _ _ ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

def fourRowFinite5Block4ActualEntry (u : ℝ) : Matrix (Fin 5) (Fin 5) ℝ := fun i j =>
  fourRowFiniteTrivialEntry 1 2 ((5 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

theorem fourRowFinite5Block4_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite5Block4Power i j k) u =
      fourRowFiniteDenominator 5 u • fourRowFinite5Block4ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite5Block4Power i j)) =
    fourRowFiniteDenominator 5 u*fourRowFinite5Block4ActualEntry u i j
  rw [fourRowFinite5Block4_polynomial_actual]
  rw [fourRowFiniteTrivialPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite5Block4_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite5Block4ActualEntry u).PosDef := by
  have hp := fourRowFinite5Block4Polynomial_posDef u hu
  rw [fourRowFinite5Block4_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 5) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
