import DR.Rectangular.FourRowFiniteData5KernelSeed0
import DR.Rectangular.FourRowFiniteData5KernelSeed1
import DR.Rectangular.FourRowFiniteData5KernelSeed2
import DR.Rectangular.FourRowFiniteData5KernelSeed3
import DR.Rectangular.FourRowFiniteData5KernelSeed4
import DR.Rectangular.FourRowFiniteData5KernelSeed5
import DR.Rectangular.FourRowFiniteData5KernelSeed6
import DR.Rectangular.FourRowFiniteData5KernelSeed7
import DR.Rectangular.FourRowFiniteData5KernelSeed8
import DR.Rectangular.FourRowFiniteData5KernelSeed9


/-! Generated by scripts/generate_four_row_finite_kernel.py.
The full compressed rows include the omitted principal coordinate.
Every coefficient of every degree-eight row polynomial is checked. -/

namespace DittertRybin

theorem fourRowFinite5_full_kernel_coefficients (s : Fin 10)
    (i : Fin (fourRowFiniteSeedFullSize s)) (d : Fin 9) :
    fourRowFiniteSeedKernelPower fourRowFiniteFamilyNumerator5 5 s i d = 0 := by
  rw [← fourRowFiniteSeedKernelPowerFast_eq]
  fin_cases s
  · exact fourRowFinite5FullKernel_0 i d
  · exact fourRowFinite5FullKernel_1 i d
  · exact fourRowFinite5FullKernel_2 i d
  · exact fourRowFinite5FullKernel_3 i d
  · exact fourRowFinite5FullKernel_4 i d
  · exact fourRowFinite5FullKernel_5 i d
  · exact fourRowFinite5FullKernel_6 i d
  · exact fourRowFinite5FullKernel_7 i d
  · exact fourRowFinite5FullKernel_8 i d
  · exact fourRowFinite5FullKernel_9 i d

end DittertRybin
