import DR.Rectangular.FourRowFiniteData50KernelSeed0
import DR.Rectangular.FourRowFiniteData50KernelSeed1
import DR.Rectangular.FourRowFiniteData50KernelSeed2
import DR.Rectangular.FourRowFiniteData50KernelSeed3
import DR.Rectangular.FourRowFiniteData50KernelSeed4
import DR.Rectangular.FourRowFiniteData50KernelSeed5
import DR.Rectangular.FourRowFiniteData50KernelSeed6
import DR.Rectangular.FourRowFiniteData50KernelSeed7
import DR.Rectangular.FourRowFiniteData50KernelSeed8
import DR.Rectangular.FourRowFiniteData50KernelSeed9


/-! Generated by scripts/generate_four_row_finite_kernel.py.
The full compressed rows include the omitted principal coordinate.
Every coefficient of every degree-eight row polynomial is checked. -/

namespace DittertRybin

theorem fourRowFinite50_full_kernel_coefficients (s : Fin 10)
    (i : Fin (fourRowFiniteSeedFullSize s)) (d : Fin 9) :
    fourRowFiniteSeedKernelPower fourRowFiniteFamilyNumerator50 50 s i d = 0 := by
  rw [← fourRowFiniteSeedKernelPowerFast_eq]
  fin_cases s
  · exact fourRowFinite50FullKernel_0 i d
  · exact fourRowFinite50FullKernel_1 i d
  · exact fourRowFinite50FullKernel_2 i d
  · exact fourRowFinite50FullKernel_3 i d
  · exact fourRowFinite50FullKernel_4 i d
  · exact fourRowFinite50FullKernel_5 i d
  · exact fourRowFinite50FullKernel_6 i d
  · exact fourRowFinite50FullKernel_7 i d
  · exact fourRowFinite50FullKernel_8 i d
  · exact fourRowFinite50FullKernel_9 i d

end DittertRybin
