import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData50
import DR.Rectangular.FourRowFiniteData50Block4Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=50; multiplier seed 1; trivial sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite50Block4ActualPower (i j : Fin 5) : Fin 8 → ℚ :=
  fourRowFiniteTrivialPower 1 1 50
    (fun key => fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key))
    [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite50Block4_power_actual : ∀ i j : Fin 5, ∀ d : Fin 10,
    fourRowFinite50Block4Power i j d = fourRowFinitePowerPad (fourRowFinite50Block4ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite50Block4_polynomial_actual (i j : Fin 5) :
    powerPolynomial (fourRowFinite50Block4Power i j) =
      fourRowFiniteTrivialPolynomial 1 1 50
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator50)
      [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3)) := by
  have he := funext (fourRowFinite50Block4_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteTrivialPower_polynomial 1 1 50 _ _ ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

def fourRowFinite50Block4ActualEntry (u : ℝ) : Matrix (Fin 5) (Fin 5) ℝ := fun i j =>
  fourRowFiniteTrivialEntry 1 2 ((50 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,0),(0,1)] ((i.val/3),(i.val%3)) ((j.val/3),(j.val%3))

theorem fourRowFinite50Block4_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite50Block4Power i j k) u =
      fourRowFiniteDenominator 50 u • fourRowFinite50Block4ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite50Block4Power i j)) =
    fourRowFiniteDenominator 50 u*fourRowFinite50Block4ActualEntry u i j
  rw [fourRowFinite50Block4_polynomial_actual]
  rw [fourRowFiniteTrivialPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite50Block4_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite50Block4ActualEntry u).PosDef := by
  have hp := fourRowFinite50Block4Polynomial_posDef u hu
  rw [fourRowFinite50Block4_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 50) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
