import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData5
import DR.Rectangular.FourRowFiniteData5Block22Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=5; multiplier seed 5; column sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite5Block22ActualPower (i j : Fin 3) : Fin 8 → ℚ :=
  fourRowFiniteColumnStandardPower 2 1 5
    (fun key => fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key))
    [(0,0),(0,1),(1,0)] i.val j.val

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite5Block22_power_actual : ∀ i j : Fin 3, ∀ d : Fin 10,
    fourRowFinite5Block22Power i j d = fourRowFinitePowerPad (fourRowFinite5Block22ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite5Block22_polynomial_actual (i j : Fin 3) :
    powerPolynomial (fourRowFinite5Block22Power i j) =
      fourRowFiniteColumnStandardPolynomial 2 1 5
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator5)
      [(0,0),(0,1),(1,0)] i.val j.val := by
  have he := funext (fourRowFinite5Block22_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteColumnStandardPower_polynomial 2 1 5 _ _ i.val j.val

def fourRowFinite5Block22ActualEntry (u : ℝ) : Matrix (Fin 3) (Fin 3) ℝ := fun i j =>
  fourRowFiniteColumnStandardEntry 2 2
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator5 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,1),(1,0)] i.val j.val

theorem fourRowFinite5Block22_actualEntry_clear (u : ℝ) (_hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite5Block22Power i j k) u =
      fourRowFiniteDenominator 5 u • fourRowFinite5Block22ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite5Block22Power i j)) =
    fourRowFiniteDenominator 5 u*fourRowFinite5Block22ActualEntry u i j
  rw [fourRowFinite5Block22_polynomial_actual]
  rw [fourRowFiniteColumnStandardPolynomial_eval ]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite5Block22_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite5Block22ActualEntry u).PosDef := by
  have hp := fourRowFinite5Block22Polynomial_posDef u hu
  rw [fourRowFinite5Block22_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 5) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
