import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData50
import DR.Rectangular.FourRowFiniteData50Block17Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=50; multiplier seed 4; row sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite50Block17ActualPower (i j : Fin 4) : Fin 8 → ℚ :=
  fourRowFiniteRowStandardPower 1 2 50
    (fun key => fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key))
    [(0,0),(0,1),(0,2)] i.val j.val

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite50Block17_power_actual : ∀ i j : Fin 4, ∀ d : Fin 10,
    fourRowFinite50Block17Power i j d = fourRowFinitePowerPad (fourRowFinite50Block17ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite50Block17_polynomial_actual (i j : Fin 4) :
    powerPolynomial (fourRowFinite50Block17Power i j) =
      fourRowFiniteRowStandardPolynomial 1 2 50
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator50)
      [(0,0),(0,1),(0,2)] i.val j.val := by
  have he := funext (fourRowFinite50Block17_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteRowStandardPower_polynomial 1 2 50 _ _ i.val j.val

def fourRowFinite50Block17ActualEntry (u : ℝ) : Matrix (Fin 4) (Fin 4) ℝ := fun i j =>
  fourRowFiniteRowStandardEntry 1 3 ((50 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,1),(0,2)] i.val j.val

theorem fourRowFinite50Block17_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite50Block17Power i j k) u =
      fourRowFiniteDenominator 50 u • fourRowFinite50Block17ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite50Block17Power i j)) =
    fourRowFiniteDenominator 50 u*fourRowFinite50Block17ActualEntry u i j
  rw [fourRowFinite50Block17_polynomial_actual]
  rw [fourRowFiniteRowStandardPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite50Block17_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite50Block17ActualEntry u).PosDef := by
  have hp := fourRowFinite50Block17Polynomial_posDef u hu
  rw [fourRowFinite50Block17_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 50) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
