import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData50
import DR.Rectangular.FourRowFiniteData50Block0Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a=50; multiplier seed 0; trivial sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def fourRowFinite50Block0ActualPower (i j : Fin 3) : Fin 8 → ℚ :=
  fourRowFiniteTrivialPower 1 0 50
    (fun key => fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key))
    [(0,0),(0,0),(0,0)] ((i.val/2),(i.val%2)) ((j.val/2),(j.val%2))

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite50Block0_power_actual : ∀ i j : Fin 3, ∀ d : Fin 10,
    fourRowFinite50Block0Power i j d = fourRowFinitePowerPad (fourRowFinite50Block0ActualPower i j) d := by
  decide +kernel

theorem fourRowFinite50Block0_polynomial_actual (i j : Fin 3) :
    powerPolynomial (fourRowFinite50Block0Power i j) =
      fourRowFiniteTrivialPolynomial 1 0 50
      (fourRowFiniteFamilyRolePolynomial fourRowFiniteFamilyNumerator50)
      [(0,0),(0,0),(0,0)] ((i.val/2),(i.val%2)) ((j.val/2),(j.val%2)) := by
  have he := funext (fourRowFinite50Block0_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFiniteTrivialPower_polynomial 1 0 50 _ _ ((i.val/2),(i.val%2)) ((j.val/2),(j.val%2))

def fourRowFinite50Block0ActualEntry (u : ℝ) : Matrix (Fin 3) (Fin 3) ℝ := fun i j =>
  fourRowFiniteTrivialEntry 1 1 ((50 : ℝ)/u)
    (fun key => fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator50 (fourRowFiniteRoleLookup key) u)
    [(0,0),(0,0),(0,0)] ((i.val/2),(i.val%2)) ((j.val/2),(j.val%2))

theorem fourRowFinite50Block0_actualEntry_clear (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => fourRowFinite50Block0Power i j k) u =
      fourRowFiniteDenominator 50 u • fourRowFinite50Block0ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial (fourRowFinite50Block0Power i j)) =
    fourRowFiniteDenominator 50 u*fourRowFinite50Block0ActualEntry u i j
  rw [fourRowFinite50Block0_polynomial_actual]
  rw [fourRowFiniteTrivialPolynomial_eval (by norm_num) (by linarith : 0 < u) hu.2]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem fourRowFinite50Block0_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    (fourRowFinite50Block0ActualEntry u).PosDef := by
  have hp := fourRowFinite50Block0Polynomial_posDef u hu
  rw [fourRowFinite50Block0_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ 50) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
