import DR.Certificates.FiniteK4OrbitData
import Mathlib.Tactic

/-! Generated by scripts/generate_four_row_finite_lookup.py.
The balanced total lookup is asserted correct only on the existing 391 keys.
Its complete inverse check uses the independent universal role catalogue. -/

namespace DittertRybin
open Certificates

def fourRowFiniteRoleLookup (key : ℕ) : Fin 391 :=
  if key < 18912 then
  if key < 3803 then
    if key < 3125 then
      if key < 652 then
        if key < 136 then
          if key < 30 then
            if key < 6 then
              if key < 1 then
                0
              else
                if key < 5 then
                  1
                else
                  2
            else
              if key < 26 then
                3
              else
                if key < 27 then
                  4
                else
                  5
          else
            if key < 130 then
              if key < 31 then
                6
              else
                if key < 32 then
                  7
                else
                  8
            else
              if key < 131 then
                9
              else
                if key < 135 then
                  10
                else
                  11
        else
          if key < 626 then
            if key < 161 then
              if key < 156 then
                12
              else
                if key < 157 then
                  13
                else
                  14
            else
              if key < 162 then
                15
              else
                if key < 625 then
                  16
                else
                  17
          else
            if key < 631 then
              if key < 627 then
                18
              else
                if key < 630 then
                  19
                else
                  20
            else
              if key < 632 then
                21
              else
                if key < 651 then
                  22
                else
                  23
      else
        if key < 757 then
          if key < 680 then
            if key < 657 then
              if key < 655 then
                24
              else
                if key < 656 then
                  25
                else
                  26
            else
              if key < 677 then
                27
              else
                if key < 678 then
                  28
                else
                  29
          else
            if key < 683 then
              if key < 681 then
                30
              else
                if key < 682 then
                  31
                else
                  32
            else
              if key < 755 then
                33
              else
                if key < 756 then
                  34
                else
                  35
        else
          if key < 786 then
            if key < 762 then
              if key < 760 then
                36
              else
                if key < 761 then
                  37
                else
                  38
            else
              if key < 781 then
                39
              else
                if key < 782 then
                  40
                else
                  41
          else
            if key < 808 then
              if key < 787 then
                42
              else
                if key < 807 then
                  43
                else
                  44
            else
              if key < 812 then
                45
              else
                if key < 813 then
                  46
                else
                  47
    else
      if key < 3386 then
        if key < 3161 then
          if key < 3151 then
            if key < 3131 then
              if key < 3126 then
                48
              else
                if key < 3130 then
                  49
                else
                  50
            else
              if key < 3135 then
                51
              else
                if key < 3136 then
                  52
                else
                  53
          else
            if key < 3156 then
              if key < 3152 then
                54
              else
                if key < 3155 then
                  55
                else
                  56
            else
              if key < 3157 then
                57
              else
                if key < 3160 then
                  58
                else
                  59
        else
          if key < 3281 then
            if key < 3256 then
              if key < 3162 then
                60
              else
                if key < 3255 then
                  61
                else
                  62
            else
              if key < 3260 then
                63
              else
                if key < 3261 then
                  64
                else
                  65
          else
            if key < 3286 then
              if key < 3282 then
                66
              else
                if key < 3285 then
                  67
                else
                  68
            else
              if key < 3287 then
                69
              else
                if key < 3385 then
                  70
                else
                  71
      else
        if key < 3757 then
          if key < 3417 then
            if key < 3411 then
              if key < 3390 then
                72
              else
                if key < 3391 then
                  73
                else
                  74
            else
              if key < 3412 then
                75
              else
                if key < 3416 then
                  76
                else
                  77
          else
            if key < 3752 then
              if key < 3750 then
                78
              else
                if key < 3751 then
                  79
                else
                  80
            else
              if key < 3755 then
                81
              else
                if key < 3756 then
                  82
                else
                  83
        else
          if key < 3780 then
            if key < 3762 then
              if key < 3760 then
                84
              else
                if key < 3761 then
                  85
                else
                  86
            else
              if key < 3776 then
                87
              else
                if key < 3777 then
                  88
                else
                  89
          else
            if key < 3785 then
              if key < 3781 then
                90
              else
                if key < 3782 then
                  91
                else
                  92
            else
              if key < 3787 then
                if key < 3786 then
                  93
                else
                  94
              else
                if key < 3802 then
                  95
                else
                  96
  else
    if key < 16958 then
      if key < 3937 then
        if key < 3885 then
          if key < 3811 then
            if key < 3807 then
              if key < 3805 then
                97
              else
                if key < 3806 then
                  98
                else
                  99
            else
              if key < 3808 then
                100
              else
                if key < 3810 then
                  101
                else
                  102
          else
            if key < 3880 then
              if key < 3812 then
                103
              else
                if key < 3813 then
                  104
                else
                  105
            else
              if key < 3881 then
                106
              else
                if key < 3882 then
                  107
                else
                  108
        else
          if key < 3911 then
            if key < 3906 then
              if key < 3886 then
                109
              else
                if key < 3887 then
                  110
                else
                  111
            else
              if key < 3907 then
                112
              else
                if key < 3910 then
                  113
                else
                  114
          else
            if key < 3933 then
              if key < 3912 then
                115
              else
                if key < 3932 then
                  116
                else
                  117
            else
              if key < 3935 then
                118
              else
                if key < 3936 then
                  119
                else
                  120
      else
        if key < 4062 then
          if key < 4016 then
            if key < 4011 then
              if key < 3938 then
                121
              else
                if key < 4010 then
                  122
                else
                  123
            else
              if key < 4012 then
                124
              else
                if key < 4015 then
                  125
                else
                  126
          else
            if key < 4037 then
              if key < 4017 then
                127
              else
                if key < 4036 then
                  128
                else
                  129
            else
              if key < 4041 then
                130
              else
                if key < 4042 then
                  131
                else
                  132
        else
          if key < 16878 then
            if key < 4068 then
              if key < 4063 then
                133
              else
                if key < 4067 then
                  134
                else
                  135
            else
              if key < 16875 then
                136
              else
                if key < 16876 then
                  137
                else
                  138
          else
            if key < 16883 then
              if key < 16880 then
                139
              else
                if key < 16881 then
                  140
                else
                  141
            else
              if key < 16954 then
                if key < 16953 then
                  142
                else
                  143
              else
                if key < 16955 then
                  144
                else
                  145
    else
      if key < 18781 then
        if key < 18750 then
          if key < 17011 then
            if key < 17006 then
              if key < 16959 then
                146
              else
                if key < 17005 then
                  147
                else
                  148
            else
              if key < 17008 then
                149
              else
                if key < 17010 then
                  150
                else
                  151
          else
            if key < 17084 then
              if key < 17013 then
                152
              else
                if key < 17083 then
                  153
                else
                  154
            else
              if key < 17088 then
                155
              else
                if key < 17089 then
                  156
                else
                  157
        else
          if key < 18760 then
            if key < 18755 then
              if key < 18751 then
                158
              else
                if key < 18752 then
                  159
                else
                  160
            else
              if key < 18756 then
                161
              else
                if key < 18757 then
                  162
                else
                  163
          else
            if key < 18776 then
              if key < 18761 then
                164
              else
                if key < 18762 then
                  165
                else
                  166
            else
              if key < 18777 then
                167
              else
                if key < 18780 then
                  168
                else
                  169
      else
        if key < 18811 then
          if key < 18803 then
            if key < 18786 then
              if key < 18782 then
                170
              else
                if key < 18785 then
                  171
                else
                  172
            else
              if key < 18787 then
                173
              else
                if key < 18802 then
                  174
                else
                  175
          else
            if key < 18807 then
              if key < 18805 then
                176
              else
                if key < 18806 then
                  177
                else
                  178
            else
              if key < 18808 then
                179
              else
                if key < 18810 then
                  180
                else
                  181
        else
          if key < 18885 then
            if key < 18880 then
              if key < 18812 then
                182
              else
                if key < 18813 then
                  183
                else
                  184
            else
              if key < 18881 then
                185
              else
                if key < 18882 then
                  186
                else
                  187
          else
            if key < 18906 then
              if key < 18886 then
                188
              else
                if key < 18887 then
                  189
                else
                  190
            else
              if key < 18910 then
                if key < 18907 then
                  191
                else
                  192
              else
                if key < 18911 then
                  193
                else
                  194
else
  if key < 84417 then
    if key < 20088 then
      if key < 20003 then
        if key < 19017 then
          if key < 18938 then
            if key < 18935 then
              if key < 18932 then
                195
              else
                if key < 18933 then
                  196
                else
                  197
            else
              if key < 18936 then
                198
              else
                if key < 18937 then
                  199
                else
                  200
          else
            if key < 19012 then
              if key < 19010 then
                201
              else
                if key < 19011 then
                  202
                else
                  203
            else
              if key < 19015 then
                204
              else
                if key < 19016 then
                  205
                else
                  206
        else
          if key < 19063 then
            if key < 19041 then
              if key < 19036 then
                207
              else
                if key < 19037 then
                  208
                else
                  209
            else
              if key < 19042 then
                210
              else
                if key < 19062 then
                  211
                else
                  212
          else
            if key < 20000 then
              if key < 19067 then
                213
              else
                if key < 19068 then
                  214
                else
                  215
            else
              if key < 20001 then
                216
              else
                if key < 20002 then
                  217
                else
                  218
      else
        if key < 20057 then
          if key < 20011 then
            if key < 20007 then
              if key < 20005 then
                219
              else
                if key < 20006 then
                  220
                else
                  221
            else
              if key < 20008 then
                222
              else
                if key < 20010 then
                  223
                else
                  224
          else
            if key < 20052 then
              if key < 20012 then
                225
              else
                if key < 20013 then
                  226
                else
                  227
            else
              if key < 20053 then
                228
              else
                if key < 20055 then
                  229
                else
                  230
        else
          if key < 20079 then
            if key < 20062 then
              if key < 20058 then
                231
              else
                if key < 20060 then
                  232
                else
                  233
            else
              if key < 20063 then
                234
              else
                if key < 20078 then
                  235
                else
                  236
          else
            if key < 20083 then
              if key < 20080 then
                237
              else
                if key < 20082 then
                  238
                else
                  239
            else
              if key < 20085 then
                if key < 20084 then
                  240
                else
                  241
              else
                if key < 20087 then
                  242
                else
                  243
    else
      if key < 20263 then
        if key < 20185 then
          if key < 20135 then
            if key < 20131 then
              if key < 20089 then
                244
              else
                if key < 20130 then
                  245
                else
                  246
            else
              if key < 20132 then
                247
              else
                if key < 20133 then
                  248
                else
                  249
          else
            if key < 20138 then
              if key < 20136 then
                250
              else
                if key < 20137 then
                  251
                else
                  252
            else
              if key < 20182 then
                253
              else
                if key < 20183 then
                  254
                else
                  255
        else
          if key < 20212 then
            if key < 20208 then
              if key < 20187 then
                256
              else
                if key < 20188 then
                  257
                else
                  258
            else
              if key < 20209 then
                259
              else
                if key < 20210 then
                  260
                else
                  261
          else
            if key < 20260 then
              if key < 20213 then
                262
              else
                if key < 20214 then
                  263
                else
                  264
            else
              if key < 20261 then
                265
              else
                if key < 20262 then
                  266
                else
                  267
      else
        if key < 20344 then
          if key < 20313 then
            if key < 20267 then
              if key < 20265 then
                268
              else
                if key < 20266 then
                  269
                else
                  270
            else
              if key < 20268 then
                271
              else
                if key < 20312 then
                  272
                else
                  273
          else
            if key < 20338 then
              if key < 20317 then
                274
              else
                if key < 20318 then
                  275
                else
                  276
            else
              if key < 20339 then
                277
              else
                if key < 20343 then
                  278
                else
                  279
        else
          if key < 84391 then
            if key < 84380 then
              if key < 84375 then
                280
              else
                if key < 84376 then
                  281
                else
                  282
            else
              if key < 84381 then
                283
              else
                if key < 84390 then
                  284
                else
                  285
          else
            if key < 84406 then
              if key < 84401 then
                286
              else
                if key < 84402 then
                  287
                else
                  288
            else
              if key < 84415 then
                if key < 84407 then
                  289
                else
                  290
              else
                if key < 84416 then
                  291
                else
                  292
  else
    if key < 85292 then
      if key < 85040 then
        if key < 85011 then
          if key < 85001 then
            if key < 84791 then
              if key < 84765 then
                293
              else
                if key < 84766 then
                  294
                else
                  295
            else
              if key < 84792 then
                296
              else
                if key < 85000 then
                  297
                else
                  298
          else
            if key < 85006 then
              if key < 85002 then
                299
              else
                if key < 85005 then
                  300
                else
                  301
            else
              if key < 85007 then
                302
              else
                if key < 85010 then
                  303
                else
                  304
        else
          if key < 85027 then
            if key < 85016 then
              if key < 85012 then
                305
              else
                if key < 85015 then
                  306
                else
                  307
            else
              if key < 85017 then
                308
              else
                if key < 85026 then
                  309
                else
                  310
          else
            if key < 85035 then
              if key < 85031 then
                311
              else
                if key < 85032 then
                  312
                else
                  313
            else
              if key < 85036 then
                314
              else
                if key < 85037 then
                  315
                else
                  316
      else
        if key < 85066 then
          if key < 85058 then
            if key < 85052 then
              if key < 85041 then
                317
              else
                if key < 85042 then
                  318
                else
                  319
            else
              if key < 85053 then
                320
              else
                if key < 85057 then
                  321
                else
                  322
          else
            if key < 85062 then
              if key < 85060 then
                323
              else
                if key < 85061 then
                  324
                else
                  325
            else
              if key < 85063 then
                326
              else
                if key < 85065 then
                  327
                else
                  328
        else
          if key < 85265 then
            if key < 85260 then
              if key < 85067 then
                329
              else
                if key < 85068 then
                  330
                else
                  331
            else
              if key < 85261 then
                332
              else
                if key < 85262 then
                  333
                else
                  334
          else
            if key < 85286 then
              if key < 85266 then
                335
              else
                if key < 85267 then
                  336
                else
                  337
            else
              if key < 85290 then
                if key < 85287 then
                  338
                else
                  339
              else
                if key < 85291 then
                  340
                else
                  341
    else
      if key < 101276 then
        if key < 85442 then
          if key < 85318 then
            if key < 85315 then
              if key < 85312 then
                342
              else
                if key < 85313 then
                  343
                else
                  344
            else
              if key < 85316 then
                345
              else
                if key < 85317 then
                  346
                else
                  347
          else
            if key < 85392 then
              if key < 85390 then
                348
              else
                if key < 85391 then
                  349
                else
                  350
            else
              if key < 85416 then
                351
              else
                if key < 85417 then
                  352
                else
                  353
        else
          if key < 101256 then
            if key < 101251 then
              if key < 85443 then
                354
              else
                if key < 101250 then
                  355
                else
                  356
            else
              if key < 101253 then
                357
              else
                if key < 101255 then
                  358
                else
                  359
          else
            if key < 101265 then
              if key < 101257 then
                360
              else
                if key < 101258 then
                  361
                else
                  362
            else
              if key < 101266 then
                363
              else
                if key < 101268 then
                  364
                else
                  365
      else
        if key < 101328 then
          if key < 101286 then
            if key < 101280 then
              if key < 101277 then
                366
              else
                if key < 101278 then
                  367
                else
                  368
            else
              if key < 101282 then
                369
              else
                if key < 101283 then
                  370
                else
                  371
          else
            if key < 101291 then
              if key < 101288 then
                372
              else
                if key < 101290 then
                  373
                else
                  374
            else
              if key < 101292 then
                375
              else
                if key < 101293 then
                  376
                else
                  377
        else
          if key < 101343 then
            if key < 101334 then
              if key < 101329 then
                378
              else
                if key < 101333 then
                  379
                else
                  380
            else
              if key < 101340 then
                381
              else
                if key < 101341 then
                  382
                else
                  383
          else
            if key < 101641 then
              if key < 101344 then
                384
              else
                if key < 101640 then
                  385
                else
                  386
            else
              if key < 101718 then
                if key < 101643 then
                  387
                else
                  388
              else
                if key < 101719 then
                  389
                else
                  390

set_option maxRecDepth 100000 in
set_option maxHeartbeats 32000000 in
theorem fourRowFiniteRoleLookup_key : ∀ k : Fin 391,
    fourRowFiniteRoleLookup
      (finiteK4RoleKeys.get (finiteK4FourRowRoleIndices.get k)) = k := by
  decide +kernel

end DittertRybin
