import DR.Rectangular.FourRowFiniteFastKernel
import DR.Rectangular.FourRowFiniteData50

/-! Generated by scripts/generate_four_row_finite_kernel.py.
One bounded full compressed-kernel check, including degree eight. -/

namespace DittertRybin
set_option Elab.async false

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite50FullKernel_2 :
    ∀ i : Fin (fourRowFiniteSeedFullSize 2), ∀ d : Fin 9,
      fourRowFiniteSeedKernelPowerFast fourRowFiniteFamilyNumerator50 50 2 i d = 0 := by
  decide +kernel

end DittertRybin
