import DR.Rectangular.FourRowFiniteFastKernel
import DR.Rectangular.FourRowFiniteData5

/-! Generated by scripts/generate_four_row_finite_kernel.py.
One bounded full compressed-kernel check, including degree eight. -/

namespace DittertRybin
set_option Elab.async false

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite5FullKernel_3 :
    ∀ i : Fin (fourRowFiniteSeedFullSize 3), ∀ d : Fin 9,
      fourRowFiniteSeedKernelPowerFast fourRowFiniteFamilyNumerator5 5 3 i d = 0 := by
  decide +kernel

end DittertRybin
