import DR.Rectangular.FourRowFiniteDiagonalKernel
import DR.Rectangular.FourRowFiniteData5

/-! Generated by scripts/generate_four_row_finite_kernel.py.
The absent row branch and cached role indices are replaced by proved identities. -/

namespace DittertRybin
set_option Elab.async false

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
private theorem fourRowFinite5FullKernelDiagonal_9 :
    ∀ i : Fin (fourRowFiniteSeedFullSize 9), ∀ d : Fin 9,
      fourRowFiniteDiagonalKernelPower fourRowFiniteFamilyNumerator5 5 i d = 0 := by
  intro i d
  change Fin 16 at i
  fin_cases i <;> fin_cases d <;> decide +kernel

theorem fourRowFinite5FullKernel_9
    (i : Fin (fourRowFiniteSeedFullSize 9)) (d : Fin 9) :
    fourRowFiniteSeedKernelPowerFast fourRowFiniteFamilyNumerator5 5 9 i d = 0 := by
  rw [←fourRowFiniteSeedKernelPowerOneRow_eq _ _ _ (by rfl)]
  rw [←fourRowFiniteDiagonalKernelPower_eq]
  exact fourRowFinite5FullKernelDiagonal_9 i d

end DittertRybin
