import DR.Certificates.FiniteFiveTuplePattern
import Mathlib.Algebra.BigOperators.Fin

/-! Generated by scripts/generate_four_row_finite_fast_pattern.py.
The complete inverse is kernel checked against the frozen actual catalogue. -/
namespace DittertRybin
open scoped BigOperators
open Certificates

def fourRowFinitePatternCode (p : Fin 5 → Fin 5) : ℕ :=
  ∑ i, (p i).val * 5^i.val

def fourRowFinitePatternLookup (key : ℕ) : Fin 52 :=
  if key < 1305 then
  if key < 425 then
    if key < 155 then
      if key < 50 then
        if key < 5 then
          0
        else
          if key < 30 then
            15
          else
            25
      else
        if key < 55 then
          5
        else
          if key < 130 then
            35
          else
            18
    else
      if key < 305 then
        if key < 180 then
          28
        else
          if key < 300 then
            39
          else
            8
      else
        if key < 380 then
          if key < 375 then
            43
          else
            2
        else
          if key < 405 then
            21
          else
            31
  else
    if key < 780 then
      if key < 655 then
        if key < 430 then
          11
        else
          if key < 630 then
            47
          else
            16
      else
        if key < 680 then
          26
        else
          if key < 755 then
            36
          else
            19
    else
      if key < 1005 then
        if key < 805 then
          29
        else
          if key < 930 then
            40
          else
            44
      else
        if key < 1055 then
          if key < 1030 then
            22
          else
            32
        else
          if key < 1300 then
            48
          else
            6
else
  if key < 2530 then
    if key < 2250 then
      if key < 1555 then
        if key < 1430 then
          37
        else
          if key < 1550 then
            41
          else
            9
      else
        if key < 1675 then
          45
        else
          if key < 1680 then
            12
          else
            49
    else
      if key < 2300 then
        if key < 2255 then
          3
        else
          if key < 2280 then
            23
          else
            33
      else
        if key < 2500 then
          if key < 2305 then
            13
          else
            50
        else
          if key < 2505 then
            1
          else
            17
  else
    if key < 2800 then
      if key < 2630 then
        if key < 2550 then
          27
        else
          if key < 2555 then
            7
          else
            38
      else
        if key < 2655 then
          20
        else
          if key < 2680 then
            30
          else
            42
    else
      if key < 2880 then
        if key < 2805 then
          10
        else
          if key < 2875 then
            46
          else
            4
      else
        if key < 2925 then
          if key < 2905 then
            24
          else
            34
        else
          if key < 2930 then
            14
          else
            51

set_option maxRecDepth 100000 in
set_option maxHeartbeats 32000000 in
theorem fourRowFinitePatternLookup_correct : ∀ k : Fin 52,
    fourRowFinitePatternLookup (fourRowFinitePatternCode (fiveTuplePatterns k)) = k := by
  decide +kernel

end DittertRybin
