import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck14 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 14 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck15 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 15 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck16 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 16 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck17 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 17 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck18 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 18 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck19 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 19 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck20 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 20 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
