import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck35 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 35 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck36 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 36 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck37 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 37 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck38 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 38 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck39 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 39 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck40 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 40 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck41 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 41 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
