import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck49 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 49 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck50 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 50 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck51 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 51 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
