import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck28 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 28 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck29 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 29 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck30 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 30 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck31 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 31 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck32 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 32 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck33 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 33 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck34 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 34 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
