import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck07 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 7 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck08 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 8 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck09 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 9 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck10 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 10 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck11 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 11 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck12 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 12 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck13 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 13 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
