import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck21 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 21 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck22 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 22 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck23 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 23 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck24 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 24 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck25 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 25 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck26 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 26 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck27 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 27 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
