import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck00 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 0 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck01 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 1 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck02 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 2 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck03 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 3 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck04 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 4 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck05 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 5 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck06 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 6 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
