import DR.Certificates.FiniteK4QuinticTemplate

/-! Generated by scripts/generate_finite_k4_quintic_checks.py.
Every row performs the literal kernel check for all52 column patterns. -/
namespace DittertRybin.Certificates
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option Elab.async false

theorem finiteK4QuinticPatternCheck42 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 42 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck43 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 43 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck44 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 44 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck45 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 45 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck46 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 46 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck47 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 47 c := by
  intro c
  fin_cases c <;> decide +kernel

theorem finiteK4QuinticPatternCheck48 :
    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect 48 c := by
  intro c
  fin_cases c <;> decide +kernel

end DittertRybin.Certificates
