#!/usr/bin/env python3
"""Collect the checked literal block theorems into the ten-seed interfaces."""
from __future__ import annotations

import argparse
import json

from generate_four_row_finite import ROOT, require
from generate_four_row_finite_physical import verified_blocks


def output():
    out = 'import DR.Rectangular.FourRowFiniteSeeds\n'
    for a in (5,50):
        for block in range(34):
            out += f'import DR.Rectangular.FourRowFiniteData{a}Block{block}Physical\n'
    out += '''
/-! Generated by scripts/generate_four_row_finite_summary.py.
These interfaces refer to the actual ten seed matrices and all closed parameter
interval points. Coverage of arbitrary physical triples is a separate step. -/

namespace DittertRybin
noncomputable section

'''
    for a in (5,50):
        records = verified_blocks(a)
        block_for = {(r['seed'],r['sector']): b for b,r in enumerate(records)}
        require(len(block_for) == 34, 'duplicate source block sector')
        out += f'''def fourRowFinite{a}RoleValue (u : ℝ) (key : ℕ) : ℝ :=
  fourRowFiniteNumeratorValue fourRowFiniteFamilyNumerator{a} (fourRowFiniteRoleLookup key) u

'''
        for sector, matrix, name in (
                ('trivial','Trivial','trivial'),('row','Row','row'),
                ('column','Column','column'),('interaction','Interaction','interaction')):
            standard = sector in ('row','interaction')
            constraint = '\n    (hr : fourRowFiniteSeedRows s < 3)' if standard else ''
            dimension = f' (({a} : ℝ)/u)' if sector in ('trivial','row') else ''
            out += f'''theorem fourRowFinite{a}_{name}_posDef (s : Fin 10) (u : ℝ)
    (hu : 1/10 ≤ u ∧ u ≤ 1){constraint} :
    (fourRowFiniteSeed{matrix}Matrix s{dimension} (fourRowFinite{a}RoleValue u)).PosDef := by
  fin_cases s
'''
            for seed in range(10):
                if (seed,sector) not in block_for:
                    require(standard and seed >= 7, 'unexpected missing sector')
                    out += '  · norm_num [fourRowFiniteSeedRows] at hr\n'
                    continue
                b = block_for[seed,sector]
                pre = f'fourRowFinite{a}Block{b}'
                out += (f'  · change ({pre}ActualEntry u).PosDef\n'
                        f'    exact {pre}_actualEntry_posDef u hu\n')
            out += '\n'
    return out+'end\nend DittertRybin\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'DR/Rectangular/FourRowFiniteCertifiedBlocks.lean'
    text = output()
    if args.check:
        require(path.exists() and path.read_text() == text, f'generated output differs: {path}')
    else:
        path.write_text(text)
    print(json.dumps({'families': 2, 'seed_matrices': 68, 'lean_bytes': len(text.encode()),
                      'mode': 'check' if args.check else 'write'}))


if __name__ == '__main__':
    main()
