#!/usr/bin/env python3
"""Generate finite relabeling witnesses, never proof conclusions.

The 33 mathematical seed multisets are read from our checked Lean catalog.
Every emitted witness is checked in OrderFourOrbitCoverage.lean by reduction
in the Lean kernel.  No external proof implementation is used.
"""
from itertools import combinations, combinations_with_replacement, permutations
from collections import Counter
from fractions import Fraction
from math import factorial
from math import comb
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
def write_if_changed(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)
source = (ROOT / "DR/Certificates/SpectralFourData.lean").read_text()
section = source.split("def spectralFourMultipliers", 1)[1].split("private noncomputable", 1)[0]
seeds = [tuple(map(int, m.split(","))) for m in re.findall(r"#\[([\d, ]+)\]", section)]
assert len(seeds) == 33
perms = tuple(permutations(range(4)))
witness = {}
for s, seed in enumerate(seeds):
    for r, rp in enumerate(perms):
        for c, cp in enumerate(perms):
            image = tuple(sorted(4 * rp[x // 4] + cp[x % 4] for x in seed))
            witness.setdefault(image, 576*s + 24*r + c)
assert len(witness) == 3876
values = [None] * 3876
for m in combinations_with_replacement(range(16), 4):
    a, b, c, d = m
    rank = a + comb(b+1, 2) + comb(c+2, 3) + comb(d+3, 4)
    assert values[rank] is None
    values[rank] = witness[m]
assert all(x is not None for x in values)

out = ["import DR.Square.OrderFourOrbitRole", "", "/-!",
       "# Finite witnesses for the 33 quartic multiplier orbits",
       "", "Generated by scripts/generate_order_four_orbits.py. Each packed integer",
       "specifies a seed, a row permutation, and a column permutation. The",
       "following coverage module checks the semantic image of every witness.",
       "-/", "", "namespace DittertRybin", "", "set_option maxRecDepth 100000", ""]
rows = ["⟨#[" + ", ".join(map(str, p)) + "], rfl⟩" for p in perms]
out += ["def orderFourLabelPermutations : Vector (Vector (Fin 4) 4) 24 :=",
        "  ⟨#[" + ", ".join(rows) + "], rfl⟩", "",
        "def orderFourLabelPermutationMap (r : Fin 24) (i : Fin 4) : Fin 4 :=",
        "  (orderFourLabelPermutations.get r).get i", "",
        "theorem orderFourLabelPermutationMap_bijective (r : Fin 24) :",
        "    Function.Bijective (orderFourLabelPermutationMap r) := by",
        "  have h : ∀ r : Fin 24, Function.Bijective (orderFourLabelPermutationMap r) := by",
        "    decide +kernel", "  exact h r", "",
        "noncomputable def orderFourLabelPermutation (r : Fin 24) : Equiv.Perm (Fin 4) :=",
        "  Equiv.ofBijective (orderFourLabelPermutationMap r)",
        "    (orderFourLabelPermutationMap_bijective r)", ""]
for k in range(0, len(values), 64):
    out += [f"private def orderFourOrbitWitnessChunk_{k//64} : Array ℕ :=",
            "  #[" + ", ".join(map(str, values[k:k+64])) + "]", ""]
out += ["private def orderFourOrbitWitnessChunks : Array (Array ℕ) :=",
        "  #[" + ", ".join(f"orderFourOrbitWitnessChunk_{k}" for k in range((len(values)+63)//64)) + "]", "",
        "def orderFourMultisetRank (a b c d : Fin 16) : ℕ :=",
        "  a.val + (b.val+1).choose 2 + (c.val+2).choose 3 + (d.val+3).choose 4", "",
        "def orderFourOrbitWitnessPacked (a b c d : Fin 16) : ℕ :=",
        "  let k := orderFourMultisetRank a b c d",
        "  (orderFourOrbitWitnessChunks.getD (k / 64) #[]).getD (k % 64) 0", "",
        "def orderFourOrbitWitness (a b c d : Fin 16) : Fin 33 × Fin 24 × Fin 24 :=",
        "  let w := orderFourOrbitWitnessPacked a b c d",
        "  (⟨w / 576 % 33, Nat.mod_lt _ (by decide)⟩,",
        "    ⟨w / 24 % 24, Nat.mod_lt _ (by decide)⟩,",
        "    ⟨w % 24, Nat.mod_lt _ (by decide)⟩)", "", "end DittertRybin", ""]
write_if_changed(ROOT / "DR/Square/OrderFourOrbitData.lean", "\n".join(out))
print(f"Generated {len(values)} witnesses from {len(seeds)} seeds.")

# Degree six is independently enumerated as physical unordered cell tuples.
# Taking one orbit at a time requires only 224 * 576 physical relabelings.
remaining = set(combinations_with_replacement(range(16), 6))
six_seeds, six_witness = [], {}
while remaining:
    seed = min(remaining)
    s = len(six_seeds)
    six_seeds.append(seed)
    for r, rp in enumerate(perms):
        for c, cp in enumerate(perms):
            image = tuple(sorted(4 * rp[x // 4] + cp[x % 4] for x in seed))
            six_witness.setdefault(image, 576*s + 24*r + c)
            remaining.discard(image)
assert len(six_seeds) == 224 and len(six_witness) == 54264
six_values = [None] * 54264
for m, w in six_witness.items():
    rank = sum(comb(a+k, k+1) for k, a in enumerate(m))
    assert six_values[rank] is None
    six_values[rank] = w
assert all(x is not None for x in six_values)
out = ["import DR.Square.OrderFourOrbitData", "", "/-!",
       "# Finite physical witnesses for the 224 sextic monomial orbits",
       "", "Generated by scripts/generate_order_four_orbits.py. The semantic",
       "coverage gates check all 54,264 unordered six-cell multisets.", "-/", "",
       "namespace DittertRybin", "", "set_option maxRecDepth 100000", ""]
rows = ["⟨#[" + ", ".join(map(str, p)) + "], rfl⟩" for p in six_seeds]
out += ["def orderFourSexticSeeds : Vector (Vector ℕ 6) 224 :=",
        "  ⟨#[" + ", ".join(rows) + "], rfl⟩", ""]
for k in range(0, len(six_values), 64):
    out += [f"private def orderFourSexticWitnessChunk_{k//64} : Array ℕ :=",
            "  #[" + ", ".join(map(str, six_values[k:k+64])) + "]", ""]
out += ["private def orderFourSexticWitnessChunks : Array (Array ℕ) :=",
        "  #[" + ", ".join(f"orderFourSexticWitnessChunk_{k}" for k in range((len(six_values)+63)//64)) + "]", "",
        "def orderFourSexticRank (a b c d e f : Fin 16) : ℕ :=",
        "  a.val + (b.val+1).choose 2 + (c.val+2).choose 3 + (d.val+3).choose 4 +",
        "    (e.val+4).choose 5 + (f.val+5).choose 6", "",
        "def orderFourSexticWitnessPacked (a b c d e f : Fin 16) : ℕ :=",
        "  let k := orderFourSexticRank a b c d e f",
        "  (orderFourSexticWitnessChunks.getD (k / 64) #[]).getD (k % 64) 0", "",
        "def orderFourSexticWitness (a b c d e f : Fin 16) : Fin 224 × Fin 24 × Fin 24 :=",
        "  let w := orderFourSexticWitnessPacked a b c d e f",
        "  (⟨w / 576 % 224, Nat.mod_lt _ (by decide)⟩,",
        "    ⟨w / 24 % 24, Nat.mod_lt _ (by decide)⟩,",
        "    ⟨w % 24, Nat.mod_lt _ (by decide)⟩)", "", "end DittertRybin", ""]
write_if_changed(ROOT / "DR/Square/OrderFourOrbitSexticData.lean", "\n".join(out))
print(f"Generated {len(six_values)} sextic witnesses from {len(six_seeds)} seeds.")

def multinomial(m):
    result = factorial(len(m))
    for k in Counter(m).values():
        result //= factorial(k)
    return result

expected = []
for m in six_seeds:
    successful = 0
    for four in set(combinations(m, 4)):
        if len({x // 4 for x in four}) == 4 or len({x % 4 for x in four}) == 4:
            rest = list(m)
            for x in four:
                rest.remove(x)
            successful += 24 * multinomial(rest)
    expected.append(Fraction(183, 1024) * multinomial(m) - successful)
out = ["import DR.Square.OrderFourPolynomialCoefficients",
       "import DR.Square.OrderFourOrbitSexticData", "", "/-!",
       "# Expected sextic coefficients and their physical monomials", "",
       "These rational values are data, not an assumed identity. Separate",
       "gates identify them with the actual gap and certificate coefficients.",
       "-/", "", "namespace DittertRybin", "", "set_option maxRecDepth 100000",
       "set_option maxHeartbeats 8000000", "",
       "def orderFourSexticSeedCells (s : Fin 224) : Multiset (Fin 16) :=",
       "  ((orderFourSexticSeeds.get s).toList.map",
       "    (fun a => (⟨a % 16, Nat.mod_lt _ (by decide)⟩ : Fin 16)) : List (Fin 16))", "",
       "theorem orderFourSexticSeedCells_card (s : Fin 224) :",
       "    (orderFourSexticSeedCells s).card = 6 := by",
       "  simp [orderFourSexticSeedCells]", ""]
for k in range(0, len(expected), 64):
    out += [f"private noncomputable def orderFourSexticExpectedChunk_{k//64} : Array ℚ :=",
            "  #[" + ", ".join(f"({v.numerator}/{v.denominator})" for v in expected[k:k+64]) + "]", ""]
out += ["private noncomputable def orderFourSexticExpectedChunks : Array (Array ℚ) :=",
        "  #[" + ", ".join(f"orderFourSexticExpectedChunk_{k}" for k in range(4)) + "]", "",
        "noncomputable def orderFourSexticExpectedCoefficient (s : Fin 224) : ℚ :=",
        "  (orderFourSexticExpectedChunks.getD (s.val / 64) #[]).getD (s.val % 64) 0", "",
        "end DittertRybin", ""]
write_if_changed(ROOT / "DR/Square/OrderFourPolynomialSexticData.lean", "\n".join(out))
