#!/usr/bin/env python3
"""Emit exact stored-coefficient to actual-block gates for selected families.

All ten coefficients, including zero padding, are kernel-checked. No sampled
evaluation or interpolation is used. Existing Gram and Bernstein modules are
inputs; this generator does not create or alter them.
"""
from __future__ import annotations

import argparse
import json
from functools import cache

from generate_four_row_finite import (
    DATA, ROOT, SOURCES, Q, catalogue, gram_block_files, require, symbolic_blocks, verify_source,
)


@cache
def verified_blocks(a):
    source = [record for record in SOURCES if record[2] == a]
    require(len(source) == 1, 'unknown source family')
    name, digest, _ = source[0]
    raw = (DATA / name).read_bytes()
    verify_source(raw, digest, name)
    values = tuple(map(Q, json.loads(raw)['coefficients']))
    require(len(values) == 391*5, 'unexpected source numerator count')
    h = tuple(values[5*i:5*i+5] for i in range(391))
    actual = [{'seed': seed, 'sector': sector, 'power_coefficients':
               [[[str(c) for c in p] for p in row] for row in matrix]}
              for seed, sector, matrix in symbolic_blocks(h,a)]
    saved = json.loads((DATA / f'blocks_{a}.json').read_text())
    require(actual == saved, 'saved block data differs from exact source reconstruction')
    return actual


def module(a, block):
    records = verified_blocks(a)
    record = records[block]
    seed, sector = record['seed'], record['sector']
    _, _, marks, _ = catalogue()
    mark = marks[seed]
    nr = 1 + max(x[0] for x in mark)
    nc = 1 + max(x[1] for x in mark)
    size = len(record['power_coefficients'])
    require(size > 0 and all(len(row) == size for row in record['power_coefficients']),
            'selected block must be nonempty and square')
    require(1 <= nr <= 3 and 1 <= nc <= 3, 'unexpected multiplier label count')
    expected = {'trivial': (nr+1)*(nc+1)-1, 'row': nc+1,
                'column': nr+1, 'interaction': 1}
    require(sector in expected and size == expected[sector], 'block dimension mismatch')
    require(sector not in ('row', 'interaction') or nr < 3, 'absent row sector was supplied')
    marked = '['+','.join(f'({i},{j})' for i,j in mark)+']'
    name = f'FourRowFiniteData{a}Block{block}'
    pre = f'fourRowFinite{a}Block{block}'
    hn = f'fourRowFiniteFamilyNumerator{a}'
    args = {'trivial': f' ((i.val/{nc+1}),(i.val%{nc+1})) ((j.val/{nc+1}),(j.val%{nc+1}))',
            'row': ' i.val j.val', 'column': ' i.val j.val', 'interaction': ''}[sector]
    middle = {'trivial': 'Trivial', 'row': 'RowStandard', 'column': 'ColumnStandard',
              'interaction': 'Interaction'}[sector]
    vector = (f'fourRowFinite{middle}Power {nr} {nc-1} {a}\n'
              f'    (fun key => {hn} (fourRowFiniteRoleLookup key))\n    {marked}{args}')
    polynomial = (f'fourRowFinite{middle}Polynomial {nr} {nc-1} {a}\n'
                  f'      (fourRowFiniteFamilyRolePolynomial {hn})\n      {marked}{args}')
    dimension = f' (({a} : ℝ)/u)' if sector in ('trivial','row') else ''
    entry = (f'fourRowFinite{middle}Entry {nr} {nc}{dimension}\n'
             f'    (fun key => fourRowFiniteNumeratorValue {hn} (fourRowFiniteRoleLookup key) u)\n'
             f'    {marked}{args}')
    eval_args = ('(by norm_num) (by linarith : 0 < u) hu.2'
                 if sector in ('trivial','row') else '')
    binders = 'i j' if sector != 'interaction' else '_i _j'
    interval_name = 'hu' if sector in ('trivial','row') else '_hu'
    return f'''import DR.Rectangular.FourRowFinitePowerBlocks
import DR.Rectangular.FourRowFiniteFamilyPolynomial
import DR.Rectangular.FourRowFiniteData{a}
import DR.Rectangular.{name}Transform

/-! Generated by scripts/generate_four_row_finite_physical.py.
Family a={a}; multiplier seed {seed}; {sector} sector.
All stored coefficients are checked against the actual cleared block formula. -/

namespace DittertRybin
open Certificates
noncomputable section

def {pre}ActualPower ({binders} : Fin {size}) : Fin 8 → ℚ :=
  {vector}

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem {pre}_power_actual : ∀ i j : Fin {size}, ∀ d : Fin 10,
    {pre}Power i j d = fourRowFinitePowerPad ({pre}ActualPower i j) d := by
  decide +kernel

theorem {pre}_polynomial_actual (i j : Fin {size}) :
    powerPolynomial ({pre}Power i j) =
      {polynomial} := by
  have he := funext ({pre}_power_actual i j)
  rw [he, fourRowFinitePowerPad_polynomial]
  exact fourRowFinite{middle}Power_polynomial {nr} {nc-1} {a} _ _{args}

def {pre}ActualEntry (u : ℝ) : Matrix (Fin {size}) (Fin {size}) ℝ := fun {binders} =>
  {entry}

theorem {pre}_actualEntry_clear (u : ℝ) ({interval_name} : 1/10 ≤ u ∧ u ≤ 1) :
    fourRowFiniteMatrixPolynomial (fun k i j => {pre}Power i j k) u =
      fourRowFiniteDenominator {a} u • {pre}ActualEntry u := by
  ext i j
  change rationalEval (fun _ => u) (powerPolynomial ({pre}Power i j)) =
    fourRowFiniteDenominator {a} u*{pre}ActualEntry u i j
  rw [{pre}_polynomial_actual]
  rw [fourRowFinite{middle}Polynomial_eval {eval_args}]
  simp_rw [fourRowFiniteFamilyRolePolynomial_eval]
  rfl

theorem {pre}_actualEntry_posDef (u : ℝ) (hu : 1/10 ≤ u ∧ u ≤ 1) :
    ({pre}ActualEntry u).PosDef := by
  have hp := {pre}Polynomial_posDef u hu
  rw [{pre}_actualEntry_clear u hu] at hp
  have hD := fourRowFiniteDenominator_pos (by norm_num : (5 : ℝ) ≤ {a}) hu.2
  have h := hp.smul (inv_pos.mpr hD)
  simpa only [smul_smul, inv_mul_cancel₀ hD.ne', one_smul] using h

end
end DittertRybin
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--block', type=int, action='append', required=True)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--with-gram', action='store_true',
                        help='also emit/check the existing exact Gram and Bernstein modules')
    args = parser.parse_args()
    outputs = []
    for block in sorted(set(args.block)):
        require(0 <= block < 34, 'block index is outside the 34-block catalogue')
        for a in (5,50):
            if args.with_gram:
                record = verified_blocks(a)[block]
                raw_block = (record['seed'], record['sector'],
                             [[tuple(map(Q,p)) for p in row] for row in record['power_coefficients']])
                gram_block_files(a,block,raw_block,args.check)
            path = ROOT / f'DR/Rectangular/FourRowFiniteData{a}Block{block}Physical.lean'
            text = module(a,block)
            require(path.with_name(path.name.replace('Physical','Transform')).exists(),
                    'Gram/Bernstein module must exist before physical linkage')
            if args.check:
                require(path.exists() and path.read_text() == text, f'generated output differs: {path}')
            else:
                path.write_text(text)
            outputs.append({'family': a, 'block': block, 'bytes': len(text.encode())})
    print(json.dumps({'mode': 'check' if args.check else 'write', 'outputs': outputs}))


if __name__ == '__main__':
    main()
