#!/usr/bin/env python3
"""Generate a balanced inverse for the frozen Bell-five pattern catalogue."""
from __future__ import annotations
import argparse
import json
import re
from generate_four_row_finite import ROOT, require


def tree(pairs,depth=1):
    if len(pairs)==1:
        return str(pairs[0][1])
    mid=len(pairs)//2
    pad='  '*depth
    return (f'if key < {pairs[mid][0]} then\n{pad}'+tree(pairs[:mid],depth+1)+
            f'\n{pad[:-2]}else\n{pad}'+tree(pairs[mid:],depth+1))


def output():
    source=(ROOT/'DR/Certificates/FiniteFiveTuplePatternData.lean').read_text()
    patterns=[tuple(map(int,s.split(','))) for s in re.findall(r'!\[([0-4,]+)\]',source)]
    require(len(patterns)==52 and len(set(patterns))==52,'Bell-five source count changed')
    require(all(len(p)==5 and all(p[i]<=i and p[p[i]]==p[i] for i in range(5))
                for p in patterns),'invalid first-position pattern')
    pairs=sorted((sum(p[i]*5**i for i in range(5)),k) for k,p in enumerate(patterns))
    return '''import DR.Certificates.FiniteFiveTuplePattern
import Mathlib.Algebra.BigOperators.Fin

/-! Generated by scripts/generate_four_row_finite_fast_pattern.py.
The complete inverse is kernel checked against the frozen actual catalogue. -/
namespace DittertRybin
open scoped BigOperators
open Certificates

def fourRowFinitePatternCode (p : Fin 5 → Fin 5) : ℕ :=
  ∑ i, (p i).val * 5^i.val

def fourRowFinitePatternLookup (key : ℕ) : Fin 52 :=
  '''+tree(pairs)+'''

set_option maxRecDepth 100000 in
set_option maxHeartbeats 32000000 in
theorem fourRowFinitePatternLookup_correct : ∀ k : Fin 52,
    fourRowFinitePatternLookup (fourRowFinitePatternCode (fiveTuplePatterns k)) = k := by
  decide +kernel

end DittertRybin
'''


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true')
    args=parser.parse_args()
    path=ROOT/'DR/Rectangular/FourRowFiniteDataFastPattern.lean'
    text=output()
    if args.check:
        require(path.exists() and path.read_text()==text,'generated fast pattern output differs')
    else:
        path.write_text(text)
    print(json.dumps({'patterns':52,'bytes':len(text.encode()),'mode':'check' if args.check else 'write'}))


if __name__=='__main__':
    main()
