#!/usr/bin/env python3
"""Emit full compressed weighted-kernel coefficient checks for both families."""
from __future__ import annotations

import argparse
import json

from itertools import product
from generate_four_row_finite import (
    ROOT, DATA, SOURCES, Q, add, mul, scale, role, catalogue, require, verify_source,
)
from generate_four_row_finite_physical import verified_blocks


def full_kernel_polynomials(h, a):
    """Exact full row polynomials, including the omitted ordinary/ordinary cell."""
    _, index, marks, _ = catalogue()
    factors = [(Q(1), -Q(c, a)) for c in (1, 2, 3)]
    denominator = mul(mul(factors[0], factors[1]), factors[2])
    result = []
    for mark in marks:
        nr = len({i for i, _ in mark})
        nc = len({j for _, j in mark})
        row_count = 4-nr
        dc = (Q(0), Q(1, a))
        for c, factor in enumerate(factors, 1):
            if c != nc:
                dc = mul(dc, factor)
        points = list(product(range(nr+1), range(nc+1)))
        for x in points:
            terms = []
            for y in points:
                row_weight = row_count if y[0] == nr else 1
                weight = (Q(a*row_weight), Q(-nc*row_weight)) if y[1] == nc else (Q(0), Q(row_weight))
                rows = [(x[0],y[0],Q(1))]
                if x[0] == y[0] == nr:
                    rows = [(nr,nr,Q(1,row_count)), (nr,nr+1,Q(row_count-1,row_count))]
                columns = [(x[1],y[1],denominator)]
                if x[1] == y[1] == nc:
                    columns = [(nc,nc,dc), (nc,nc+1,add(denominator,scale(dc,-1)))]
                for i,k,wr in rows:
                    if wr:
                        for j,l,wc in columns:
                            terms.append(scale(mul(weight,mul(wc,h[index[role(mark+((i,j),(k,l)))]])),wr))
            result.append(add(*terms))
    return result


def verify_kernel(a):
    name,digest,_ = next(record for record in SOURCES if record[2] == a)
    raw = (DATA/name).read_bytes()
    verify_source(raw,digest,name)
    values = tuple(map(Q,json.loads(raw)['coefficients']))
    require(len(values) == 391*5,'unexpected numerator count')
    h = tuple(values[5*i:5*i+5] for i in range(391))
    rows = full_kernel_polynomials(h,a)
    require(len(rows) == 90,'unexpected full compressed row count')
    require(all(len(p) <= 9 for p in rows),'full row degree exceeds eight')
    require(all(all(c == 0 for c in p) for p in rows),'nonzero full weighted-kernel row')
    mutated = list(h)
    mutated[0] = (h[0][0]+1,*h[0][1:])
    require(any(any(c != 0 for c in p) for p in full_kernel_polynomials(tuple(mutated),a)),
            'unit numerator mutation escaped the full weighted-kernel control')


def seed_output(a, seed):
    if seed == 9:
        return f'''import DR.Rectangular.FourRowFiniteDiagonalKernel
import DR.Rectangular.FourRowFiniteData{a}

/-! Generated by scripts/generate_four_row_finite_kernel.py.
The absent row branch and cached role indices are replaced by proved identities. -/

namespace DittertRybin
set_option Elab.async false

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
private theorem fourRowFinite{a}FullKernelDiagonal_9 :
    ∀ i : Fin (fourRowFiniteSeedFullSize 9), ∀ d : Fin 9,
      fourRowFiniteDiagonalKernelPower fourRowFiniteFamilyNumerator{a} {a} i d = 0 := by
  intro i d
  change Fin 16 at i
  fin_cases i <;> fin_cases d <;> decide +kernel

theorem fourRowFinite{a}FullKernel_9
    (i : Fin (fourRowFiniteSeedFullSize 9)) (d : Fin 9) :
    fourRowFiniteSeedKernelPowerFast fourRowFiniteFamilyNumerator{a} {a} 9 i d = 0 := by
  rw [←fourRowFiniteSeedKernelPowerOneRow_eq _ _ _ (by rfl)]
  rw [←fourRowFiniteDiagonalKernelPower_eq]
  exact fourRowFinite{a}FullKernelDiagonal_9 i d

end DittertRybin
'''
    return f'''import DR.Rectangular.FourRowFiniteFastKernel
import DR.Rectangular.FourRowFiniteData{a}

/-! Generated by scripts/generate_four_row_finite_kernel.py.
One bounded full compressed-kernel check, including degree eight. -/

namespace DittertRybin
set_option Elab.async false

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFinite{a}FullKernel_{seed} :
    ∀ i : Fin (fourRowFiniteSeedFullSize {seed}), ∀ d : Fin 9,
      fourRowFiniteSeedKernelPowerFast fourRowFiniteFamilyNumerator{a} {a} {seed} i d = 0 := by
  decide +kernel

end DittertRybin
'''


def output(a):
    verified_blocks(a)
    verify_kernel(a)
    out = ''.join(f'import DR.Rectangular.FourRowFiniteData{a}KernelSeed{s}\n' for s in range(10))
    out += '''

/-! Generated by scripts/generate_four_row_finite_kernel.py.
The full compressed rows include the omitted principal coordinate.
Every coefficient of every degree-eight row polynomial is checked. -/

namespace DittertRybin

'''
    out += f'''theorem fourRowFinite{a}_full_kernel_coefficients (s : Fin 10)
    (i : Fin (fourRowFiniteSeedFullSize s)) (d : Fin 9) :
    fourRowFiniteSeedKernelPower fourRowFiniteFamilyNumerator{a} {a} s i d = 0 := by
  rw [← fourRowFiniteSeedKernelPowerFast_eq]
  fin_cases s
'''
    for seed in range(10):
        out += f'  · exact fourRowFinite{a}FullKernel_{seed} i d\n'
    return out+'\nend DittertRybin\n'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    records = []
    for a in (5,50):
        files = {f'DR/Rectangular/FourRowFiniteData{a}FullKernel.lean':output(a)}
        for seed in range(10):
            files[f'DR/Rectangular/FourRowFiniteData{a}KernelSeed{seed}.lean'] = seed_output(a,seed)
        for name,text in files.items():
            path = ROOT/name
            if args.check:
                require(path.exists() and path.read_text() == text, f'generated output differs: {path}')
            elif not path.exists() or path.read_text() != text:
                path.write_text(text)
        records.append({'family': a, 'rows': 90, 'coefficients': 810, 'modules':len(files),
                        'bytes': sum(len(text.encode()) for text in files.values())})
    print(json.dumps({'mode': 'check' if args.check else 'write', 'families': records}))


if __name__ == '__main__':
    main()
