#!/usr/bin/env python3
"""Emit serialized kernel checks for every literal quintic pattern pair.

Each proof row checks all 52 column patterns against the actual role, weight,
slot-fiber and deleted-success formulas. Splitting rows into modules limits
concurrent elaboration; no finite check is replaced by a generator assertion.
"""
from __future__ import annotations
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BATCH_SIZE = 7


def render():
    outputs = {}
    imports = []
    for lo in range(0, 52, BATCH_SIZE):
        hi = min(51, lo + BATCH_SIZE - 1)
        name = f'FiniteK4QuinticChecks.Rows{lo:02d}To{hi:02d}'
        imports.append(f'import DR.Certificates.{name}')
        lines = [
            'import DR.Certificates.FiniteK4QuinticTemplate', '',
            '/-! Generated by scripts/generate_finite_k4_quintic_checks.py.',
            'Every row performs the literal kernel check for all52 column patterns. -/',
            'namespace DittertRybin.Certificates',
            'set_option maxRecDepth 100000',
            'set_option maxHeartbeats 0',
            'set_option Elab.async false', '',
        ]
        for row in range(lo, hi + 1):
            lines += [
                f'theorem finiteK4QuinticPatternCheck{row:02d} :',
                f'    ∀ c : Fin 52, FiniteK4QuinticPatternCorrect {row} c := by',
                '  intro c', '  fin_cases c <;> decide +kernel', '',
            ]
        lines += ['end DittertRybin.Certificates', '']
        outputs[ROOT / 'DR' / 'Certificates' / (name.replace('.', '/') + '.lean')] = '\n'.join(lines)
    lines = imports + [
        '', '/-! Complete literal 52-by-52 quintic coefficient-pattern gates. -/',
        'namespace DittertRybin.Certificates', '',
        'theorem finiteK4QuinticPattern_correct : ∀ r c : Fin 52,',
        '    FiniteK4QuinticPatternCorrect r c := by',
        '  intro r', '  fin_cases r',
    ]
    lines += [f'  · exact finiteK4QuinticPatternCheck{row:02d}' for row in range(52)]
    lines += ['', 'end DittertRybin.Certificates', '']
    outputs[ROOT / 'DR' / 'Certificates' / 'FiniteK4QuinticChecks.lean'] = '\n'.join(lines)
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    outputs = render()
    for path, text in outputs.items():
        if args.check:
            if not path.is_file() or path.read_text() != text:
                raise SystemExit(f'Generated kernel checks differ: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    print(f'{"Checked" if args.check else "Generated"} {len(outputs)} modules: all52 rows, all2704 pattern pairs')


if __name__ == '__main__':
    main()
