#!/usr/bin/env python3
"""Generate a balanced lookup for the existing 391-key four-row catalogue.

The generated Lean theorem checks every inverse value against the independent
universal catalogue. The function is total; no meaning is assigned to its
values outside the catalogue.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from generate_four_row_finite import DATA, ROOT, catalogue, key_number, require


def balanced(keys, first=0, depth=1):
    if len(keys) == 1:
        return str(first)
    mid = len(keys) // 2
    pad = '  ' * depth
    return (f'if key < {keys[mid]} then\n{pad}'
            + balanced(keys[:mid], first, depth + 1)
            + f'\n{pad[:-2]}else\n{pad}'
            + balanced(keys[mid:], first + mid, depth + 1))


def output():
    roles, _, _, _ = catalogue()
    keys = [key_number(role) for role in roles]
    require(len(keys) == 391 and keys == sorted(set(keys)),
            'four-row key count or strict ordering changed')
    saved = json.loads((DATA / 'catalogue.json').read_text())
    require(keys == saved['role_keys'], 'saved role catalogue differs from reconstruction')
    return '''import DR.Certificates.FiniteK4OrbitData
import Mathlib.Tactic

/-! Generated by scripts/generate_four_row_finite_lookup.py.
The balanced total lookup is asserted correct only on the existing 391 keys.
Its complete inverse check uses the independent universal role catalogue. -/

namespace DittertRybin
open Certificates

def fourRowFiniteRoleLookup (key : ℕ) : Fin 391 :=
  ''' + balanced(keys) + '''

set_option maxRecDepth 100000 in
set_option maxHeartbeats 32000000 in
theorem fourRowFiniteRoleLookup_key : ∀ k : Fin 391,
    fourRowFiniteRoleLookup
      (finiteK4RoleKeys.get (finiteK4FourRowRoleIndices.get k)) = k := by
  decide +kernel

end DittertRybin
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT / 'DR/Rectangular/FourRowFiniteDataLookup.lean'
    text = output()
    if args.check:
        require(path.exists() and path.read_text() == text, f'generated output differs: {path}')
    else:
        path.write_text(text)
    print(json.dumps({'role_keys': 391, 'comparisons': 390, 'lean_bytes': len(text.encode()),
                      'mode': 'check' if args.check else 'write'}))


if __name__ == '__main__':
    main()
