#!/usr/bin/env python3
"""Cache the 400 exact diagonal-seed role indices; Lean checks every entry."""
from __future__ import annotations

import argparse
import json

from generate_four_row_finite import ROOT, catalogue, require, role


def output():
    _, index, marks, _ = catalogue()
    mark = marks[9]
    require(mark == ((0, 0), (1, 1), (2, 2)), 'diagonal seed changed')
    rows = [[index[role(mark + ((i // 5, i % 5), (j // 5, j % 5)))]
             for j in range(20)] for i in range(20)]
    require(all(0 <= k < 391 for row in rows for k in row), 'invalid cached index')
    text = '''import DR.Rectangular.FourRowFiniteFastKernelOneRow

/-! Generated by scripts/generate_four_row_finite_diagonal_cache.py.
Each cached index is checked against the actual equality-pattern role evaluator. -/

namespace DittertRybin
set_option Elab.async false

private def fourRowFiniteDiagonalRoleRows : Array (Array (Fin 391)) :=
  #[''' + ',\n    '.join('#[' + ','.join(map(str, row)) + ']' for row in rows) + ''']

def fourRowFiniteDiagonalRoleIndex (i j c d : ℕ) : Fin 391 :=
  (fourRowFiniteDiagonalRoleRows.getD (5*i+c) #[]).getD (5*j+d) 0

set_option maxRecDepth 100000 in
set_option maxHeartbeats 64000000 in
theorem fourRowFiniteDiagonalRoleIndex_correct :
    ∀ i j : Fin 4, ∀ c d : Fin 5,
      fourRowFiniteDiagonalRoleIndex i j c d =
        fourRowFiniteRoleLookup (fourRowFiniteSeedFastKey 9 ((i : ℕ),c) ((j : ℕ),d)) := by
  decide +kernel

end DittertRybin
'''
    return text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    path = ROOT/'DR/Rectangular/FourRowFiniteDiagonalCache.lean'
    text = output()
    if args.check:
        require(path.exists() and path.read_text() == text, 'diagonal cache output differs')
    elif not path.exists() or path.read_text() != text:
        path.write_text(text)
    print(json.dumps({'entries': 400, 'bytes': len(text.encode()),
                      'mode': 'check' if args.check else 'write'}))


if __name__ == '__main__':
    main()
