#!/usr/bin/env python3
"""Reproduce the equality patterns and literal multiplier-triple K4 role keys.

Only finite set partitions and permutations enter this catalogue. Coefficients
and positive-semidefinite claims are separate inputs and checks.
"""
from argparse import ArgumentParser
from itertools import permutations, product
from pathlib import Path

PATTERNS = tuple(p for p in product(range(5), repeat=5)
                 if all(p[i] <= i and p[p[i]] == p[i] for i in range(5)))
ORDERS = tuple(p + q for p in ((0,1,2),(1,0,2),(1,2,0),(0,2,1),(2,0,1),(2,1,0))
               for q in ((3,4),(4,3)))


def labels(seq):
    seen, result = {}, []
    for x in seq:
        seen.setdefault(x, len(seen))
        result.append(seen[x])
    return result


def normalized(cells):
    rows, cols, packed = {}, {}, 0
    for i, j in cells:
        rows.setdefault(i, len(rows))
        cols.setdefault(j, len(cols))
        packed = 25 * packed + 5 * rows[i] + cols[j]
    return packed


def role_key(cells):
    return min(normalized(p + q) for p in permutations(cells[:3])
               for q in permutations(cells[3:]))


def vec(values):
    return '#v[' + ','.join(map(str, values)) + ']'


def render():
    if len(PATTERNS) != 52 or PATTERNS[-1] != tuple(range(5)):
        raise ArithmeticError('Bell-five catalogue mismatch')
    expected_orders = {p + q for p in permutations((0,1,2)) for q in ((3,4),(4,3))}
    if len(ORDERS) != 12 or set(ORDERS) != expected_orders:
        raise ArithmeticError('Missing, repeated or mixed multiplier/quadratic position order')
    key_table = [[role_key(tuple(zip(r, c))) for c in PATTERNS] for r in PATTERNS]
    keys = sorted({x for row in key_table for x in row})
    four_keys = sorted({x for row in key_table[:-1] for x in row})
    square_four_keys = {x for row in key_table[:-1] for x in row[:-1]}
    if (len(keys), len(four_keys), len(square_four_keys)) != (407, 391, 376):
        raise ArithmeticError('Incorrect universal/four-row/four-square role counts')
    index = {key: i for i, key in enumerate(keys)}
    four_index = {key: i for i, key in enumerate(four_keys)}
    witnesses = {}
    four_witnesses = {}
    for r, row in enumerate(key_table):
        for c, key in enumerate(row):
            witnesses.setdefault(key, (r, c))
            if r < 51:
                four_witnesses.setdefault(key, (r, c))
    patterns = '''import DR.Certificates.FiniteTuplePattern
import Mathlib.Data.Vector.Basic

/-! Generated by scripts/generate_finite_k4_orbits.py --check.
All 52 equality patterns of five positions, in lexicographic first-position order. -/

namespace DittertRybin.Certificates

def fiveTuplePatterns : Fin 52 → (Fin 5 → Fin 5) :=
  ![''' + ',\n    '.join('![' + ','.join(map(str, p)) + ']' for p in PATTERNS) + ''']

end DittertRybin.Certificates
'''
    roles = '''import DR.Certificates.FiniteFiveTuplePatternData

/-! Generated by scripts/generate_finite_k4_orbits.py --check.
Keys are lexicographically sorted after minimizing the six multiplier and
two quadratic-position orders. The 51 first rows are the four-row restriction. -/

namespace DittertRybin.Certificates

set_option maxRecDepth 10000

def finiteK4RoleKeys : Vector Nat 407 :=
  ''' + vec(keys) + '''

def finiteK4FourRowRoleIndices : Vector (Fin 407) 391 :=
  ''' + vec(index[k] for k in four_keys) + '''

def finiteK4RoleTable : Vector (Vector (Fin 407) 52) 52 :=
  #v[''' + ',\n    '.join(vec(index[k] for k in row) for row in key_table) + ''']

def finiteK4RoleWitnesses : Vector (Fin 52 × Fin 52) 407 :=
  ''' + vec('('+str(witnesses[k][0])+','+str(witnesses[k][1])+')' for k in keys) + '''

def finiteK4FourRowRoleTable : Vector (Vector (Fin 391) 52) 51 :=
  #v[''' + ',\n    '.join(vec(four_index[k] for k in row) for row in key_table[:-1]) + ''']

def finiteK4FourRowRoleWitnesses : Vector (Fin 51 × Fin 52) 391 :=
  ''' + vec('('+str(four_witnesses[k][0])+','+str(four_witnesses[k][1])+')' for k in four_keys) + '''

end DittertRybin.Certificates
'''
    axis = '''import DR.Certificates.FiniteFiveTuplePatternData

/-! Generated independent one-axis normalizations for all twelve position orders. -/
namespace DittertRybin.Certificates

def finiteK4PositionOrders : Fin 12 → List (Fin 5) :=
  ![''' + ','.join('['+','.join(map(str,o))+']' for o in ORDERS) + ''']

def finiteK4AxisLabels : Vector (Vector (List Nat) 12) 52 :=
  #v[''' + ',\n    '.join(vec('['+','.join(map(str, labels(p[i] for i in o)))+']'
                              for o in ORDERS) for p in PATTERNS) + ''']

end DittertRybin.Certificates
'''
    checks = '''import DR.Certificates.FiniteK4OrbitData
import DR.Certificates.FiniteK4RoleCache

/-! Generated literal role-formula checks. Each row is checked separately
by Lean's kernel; the final theorem covers all 2704 pattern pairs. -/

namespace DittertRybin.Certificates
set_option maxRecDepth 10000
set_option maxHeartbeats 0

'''
    for r in range(52):
        checks += f'''private theorem finiteK4RoleCheck{r:02d} : ∀ c : Fin 52,
    finiteK4CachedRoleKey {r} c =
      finiteK4RoleKeys.get ((finiteK4RoleTable.get {r}).get c) := by
  decide +kernel

'''
    checks += '''theorem finiteK4RoleTable_correct (r c : Fin 52) :
    finiteK4TupleRoleKey (finiteK4PatternCell r c) =
      finiteK4RoleKeys.get ((finiteK4RoleTable.get r).get c) := by
  rw [finiteK4TupleRoleKey_pattern_cache]
  fin_cases r
'''
    checks += ''.join(f'  · exact finiteK4RoleCheck{r:02d} c\n' for r in range(52))
    checks += '\nend DittertRybin.Certificates\n'
    return {'FiniteFiveTuplePatternData.lean': patterns, 'FiniteK4OrbitData.lean': roles,
            'FiniteK4AxisData.lean': axis, 'FiniteK4OrbitChecks.lean': checks}


def main():
    parser = ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    dest = Path(__file__).resolve().parent.parent / 'DR/Certificates'
    for name, content in render().items():
        path = dest / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise ArithmeticError(f'Generated catalogue changed: {path}')
        elif not path.exists() or path.read_text() != content:
            path.write_text(content)
    print('52 patterns; 407 universal, 391 four-row and 376 four-square roles reproduce')


if __name__ == '__main__':
    main()
