import DR.Square.OrderFourSexticChecks.Rows000To015
import DR.Square.OrderFourSexticChecks.Rows016To031
import DR.Square.OrderFourSexticChecks.Rows032To047
import DR.Square.OrderFourSexticChecks.Rows048To063
import DR.Square.OrderFourSexticChecks.Rows064To079
import DR.Square.OrderFourSexticChecks.Rows080To095
import DR.Square.OrderFourSexticChecks.Rows096To111
import DR.Square.OrderFourSexticChecks.Rows112To127
import DR.Square.OrderFourSexticChecks.Rows128To143
import DR.Square.OrderFourSexticChecks.Rows144To159
import DR.Square.OrderFourSexticChecks.Rows160To175
import DR.Square.OrderFourSexticChecks.Rows176To191
import DR.Square.OrderFourSexticChecks.Rows192To207
import DR.Square.OrderFourSexticChecks.Rows208To223

namespace DittertRybin

set_option maxRecDepth 100000
set_option maxHeartbeats 128000000
set_option Elab.async false

theorem orderFourSexticEntryKey (s : Fin 224) : orderFourSexticEntryKeyValid s := by
  fin_cases s
  · exact orderFourSexticEntryKey_0
  · exact orderFourSexticEntryKey_1
  · exact orderFourSexticEntryKey_2
  · exact orderFourSexticEntryKey_3
  · exact orderFourSexticEntryKey_4
  · exact orderFourSexticEntryKey_5
  · exact orderFourSexticEntryKey_6
  · exact orderFourSexticEntryKey_7
  · exact orderFourSexticEntryKey_8
  · exact orderFourSexticEntryKey_9
  · exact orderFourSexticEntryKey_10
  · exact orderFourSexticEntryKey_11
  · exact orderFourSexticEntryKey_12
  · exact orderFourSexticEntryKey_13
  · exact orderFourSexticEntryKey_14
  · exact orderFourSexticEntryKey_15
  · exact orderFourSexticEntryKey_16
  · exact orderFourSexticEntryKey_17
  · exact orderFourSexticEntryKey_18
  · exact orderFourSexticEntryKey_19
  · exact orderFourSexticEntryKey_20
  · exact orderFourSexticEntryKey_21
  · exact orderFourSexticEntryKey_22
  · exact orderFourSexticEntryKey_23
  · exact orderFourSexticEntryKey_24
  · exact orderFourSexticEntryKey_25
  · exact orderFourSexticEntryKey_26
  · exact orderFourSexticEntryKey_27
  · exact orderFourSexticEntryKey_28
  · exact orderFourSexticEntryKey_29
  · exact orderFourSexticEntryKey_30
  · exact orderFourSexticEntryKey_31
  · exact orderFourSexticEntryKey_32
  · exact orderFourSexticEntryKey_33
  · exact orderFourSexticEntryKey_34
  · exact orderFourSexticEntryKey_35
  · exact orderFourSexticEntryKey_36
  · exact orderFourSexticEntryKey_37
  · exact orderFourSexticEntryKey_38
  · exact orderFourSexticEntryKey_39
  · exact orderFourSexticEntryKey_40
  · exact orderFourSexticEntryKey_41
  · exact orderFourSexticEntryKey_42
  · exact orderFourSexticEntryKey_43
  · exact orderFourSexticEntryKey_44
  · exact orderFourSexticEntryKey_45
  · exact orderFourSexticEntryKey_46
  · exact orderFourSexticEntryKey_47
  · exact orderFourSexticEntryKey_48
  · exact orderFourSexticEntryKey_49
  · exact orderFourSexticEntryKey_50
  · exact orderFourSexticEntryKey_51
  · exact orderFourSexticEntryKey_52
  · exact orderFourSexticEntryKey_53
  · exact orderFourSexticEntryKey_54
  · exact orderFourSexticEntryKey_55
  · exact orderFourSexticEntryKey_56
  · exact orderFourSexticEntryKey_57
  · exact orderFourSexticEntryKey_58
  · exact orderFourSexticEntryKey_59
  · exact orderFourSexticEntryKey_60
  · exact orderFourSexticEntryKey_61
  · exact orderFourSexticEntryKey_62
  · exact orderFourSexticEntryKey_63
  · exact orderFourSexticEntryKey_64
  · exact orderFourSexticEntryKey_65
  · exact orderFourSexticEntryKey_66
  · exact orderFourSexticEntryKey_67
  · exact orderFourSexticEntryKey_68
  · exact orderFourSexticEntryKey_69
  · exact orderFourSexticEntryKey_70
  · exact orderFourSexticEntryKey_71
  · exact orderFourSexticEntryKey_72
  · exact orderFourSexticEntryKey_73
  · exact orderFourSexticEntryKey_74
  · exact orderFourSexticEntryKey_75
  · exact orderFourSexticEntryKey_76
  · exact orderFourSexticEntryKey_77
  · exact orderFourSexticEntryKey_78
  · exact orderFourSexticEntryKey_79
  · exact orderFourSexticEntryKey_80
  · exact orderFourSexticEntryKey_81
  · exact orderFourSexticEntryKey_82
  · exact orderFourSexticEntryKey_83
  · exact orderFourSexticEntryKey_84
  · exact orderFourSexticEntryKey_85
  · exact orderFourSexticEntryKey_86
  · exact orderFourSexticEntryKey_87
  · exact orderFourSexticEntryKey_88
  · exact orderFourSexticEntryKey_89
  · exact orderFourSexticEntryKey_90
  · exact orderFourSexticEntryKey_91
  · exact orderFourSexticEntryKey_92
  · exact orderFourSexticEntryKey_93
  · exact orderFourSexticEntryKey_94
  · exact orderFourSexticEntryKey_95
  · exact orderFourSexticEntryKey_96
  · exact orderFourSexticEntryKey_97
  · exact orderFourSexticEntryKey_98
  · exact orderFourSexticEntryKey_99
  · exact orderFourSexticEntryKey_100
  · exact orderFourSexticEntryKey_101
  · exact orderFourSexticEntryKey_102
  · exact orderFourSexticEntryKey_103
  · exact orderFourSexticEntryKey_104
  · exact orderFourSexticEntryKey_105
  · exact orderFourSexticEntryKey_106
  · exact orderFourSexticEntryKey_107
  · exact orderFourSexticEntryKey_108
  · exact orderFourSexticEntryKey_109
  · exact orderFourSexticEntryKey_110
  · exact orderFourSexticEntryKey_111
  · exact orderFourSexticEntryKey_112
  · exact orderFourSexticEntryKey_113
  · exact orderFourSexticEntryKey_114
  · exact orderFourSexticEntryKey_115
  · exact orderFourSexticEntryKey_116
  · exact orderFourSexticEntryKey_117
  · exact orderFourSexticEntryKey_118
  · exact orderFourSexticEntryKey_119
  · exact orderFourSexticEntryKey_120
  · exact orderFourSexticEntryKey_121
  · exact orderFourSexticEntryKey_122
  · exact orderFourSexticEntryKey_123
  · exact orderFourSexticEntryKey_124
  · exact orderFourSexticEntryKey_125
  · exact orderFourSexticEntryKey_126
  · exact orderFourSexticEntryKey_127
  · exact orderFourSexticEntryKey_128
  · exact orderFourSexticEntryKey_129
  · exact orderFourSexticEntryKey_130
  · exact orderFourSexticEntryKey_131
  · exact orderFourSexticEntryKey_132
  · exact orderFourSexticEntryKey_133
  · exact orderFourSexticEntryKey_134
  · exact orderFourSexticEntryKey_135
  · exact orderFourSexticEntryKey_136
  · exact orderFourSexticEntryKey_137
  · exact orderFourSexticEntryKey_138
  · exact orderFourSexticEntryKey_139
  · exact orderFourSexticEntryKey_140
  · exact orderFourSexticEntryKey_141
  · exact orderFourSexticEntryKey_142
  · exact orderFourSexticEntryKey_143
  · exact orderFourSexticEntryKey_144
  · exact orderFourSexticEntryKey_145
  · exact orderFourSexticEntryKey_146
  · exact orderFourSexticEntryKey_147
  · exact orderFourSexticEntryKey_148
  · exact orderFourSexticEntryKey_149
  · exact orderFourSexticEntryKey_150
  · exact orderFourSexticEntryKey_151
  · exact orderFourSexticEntryKey_152
  · exact orderFourSexticEntryKey_153
  · exact orderFourSexticEntryKey_154
  · exact orderFourSexticEntryKey_155
  · exact orderFourSexticEntryKey_156
  · exact orderFourSexticEntryKey_157
  · exact orderFourSexticEntryKey_158
  · exact orderFourSexticEntryKey_159
  · exact orderFourSexticEntryKey_160
  · exact orderFourSexticEntryKey_161
  · exact orderFourSexticEntryKey_162
  · exact orderFourSexticEntryKey_163
  · exact orderFourSexticEntryKey_164
  · exact orderFourSexticEntryKey_165
  · exact orderFourSexticEntryKey_166
  · exact orderFourSexticEntryKey_167
  · exact orderFourSexticEntryKey_168
  · exact orderFourSexticEntryKey_169
  · exact orderFourSexticEntryKey_170
  · exact orderFourSexticEntryKey_171
  · exact orderFourSexticEntryKey_172
  · exact orderFourSexticEntryKey_173
  · exact orderFourSexticEntryKey_174
  · exact orderFourSexticEntryKey_175
  · exact orderFourSexticEntryKey_176
  · exact orderFourSexticEntryKey_177
  · exact orderFourSexticEntryKey_178
  · exact orderFourSexticEntryKey_179
  · exact orderFourSexticEntryKey_180
  · exact orderFourSexticEntryKey_181
  · exact orderFourSexticEntryKey_182
  · exact orderFourSexticEntryKey_183
  · exact orderFourSexticEntryKey_184
  · exact orderFourSexticEntryKey_185
  · exact orderFourSexticEntryKey_186
  · exact orderFourSexticEntryKey_187
  · exact orderFourSexticEntryKey_188
  · exact orderFourSexticEntryKey_189
  · exact orderFourSexticEntryKey_190
  · exact orderFourSexticEntryKey_191
  · exact orderFourSexticEntryKey_192
  · exact orderFourSexticEntryKey_193
  · exact orderFourSexticEntryKey_194
  · exact orderFourSexticEntryKey_195
  · exact orderFourSexticEntryKey_196
  · exact orderFourSexticEntryKey_197
  · exact orderFourSexticEntryKey_198
  · exact orderFourSexticEntryKey_199
  · exact orderFourSexticEntryKey_200
  · exact orderFourSexticEntryKey_201
  · exact orderFourSexticEntryKey_202
  · exact orderFourSexticEntryKey_203
  · exact orderFourSexticEntryKey_204
  · exact orderFourSexticEntryKey_205
  · exact orderFourSexticEntryKey_206
  · exact orderFourSexticEntryKey_207
  · exact orderFourSexticEntryKey_208
  · exact orderFourSexticEntryKey_209
  · exact orderFourSexticEntryKey_210
  · exact orderFourSexticEntryKey_211
  · exact orderFourSexticEntryKey_212
  · exact orderFourSexticEntryKey_213
  · exact orderFourSexticEntryKey_214
  · exact orderFourSexticEntryKey_215
  · exact orderFourSexticEntryKey_216
  · exact orderFourSexticEntryKey_217
  · exact orderFourSexticEntryKey_218
  · exact orderFourSexticEntryKey_219
  · exact orderFourSexticEntryKey_220
  · exact orderFourSexticEntryKey_221
  · exact orderFourSexticEntryKey_222
  · exact orderFourSexticEntryKey_223

theorem orderFourSexticTableCoefficient_eq_expected (s : Fin 224) :
    orderFourSexticTableCoefficient s = orderFourSexticExpectedCoefficient s := by
  fin_cases s
  · exact orderFourSexticTableCoefficient_0
  · exact orderFourSexticTableCoefficient_1
  · exact orderFourSexticTableCoefficient_2
  · exact orderFourSexticTableCoefficient_3
  · exact orderFourSexticTableCoefficient_4
  · exact orderFourSexticTableCoefficient_5
  · exact orderFourSexticTableCoefficient_6
  · exact orderFourSexticTableCoefficient_7
  · exact orderFourSexticTableCoefficient_8
  · exact orderFourSexticTableCoefficient_9
  · exact orderFourSexticTableCoefficient_10
  · exact orderFourSexticTableCoefficient_11
  · exact orderFourSexticTableCoefficient_12
  · exact orderFourSexticTableCoefficient_13
  · exact orderFourSexticTableCoefficient_14
  · exact orderFourSexticTableCoefficient_15
  · exact orderFourSexticTableCoefficient_16
  · exact orderFourSexticTableCoefficient_17
  · exact orderFourSexticTableCoefficient_18
  · exact orderFourSexticTableCoefficient_19
  · exact orderFourSexticTableCoefficient_20
  · exact orderFourSexticTableCoefficient_21
  · exact orderFourSexticTableCoefficient_22
  · exact orderFourSexticTableCoefficient_23
  · exact orderFourSexticTableCoefficient_24
  · exact orderFourSexticTableCoefficient_25
  · exact orderFourSexticTableCoefficient_26
  · exact orderFourSexticTableCoefficient_27
  · exact orderFourSexticTableCoefficient_28
  · exact orderFourSexticTableCoefficient_29
  · exact orderFourSexticTableCoefficient_30
  · exact orderFourSexticTableCoefficient_31
  · exact orderFourSexticTableCoefficient_32
  · exact orderFourSexticTableCoefficient_33
  · exact orderFourSexticTableCoefficient_34
  · exact orderFourSexticTableCoefficient_35
  · exact orderFourSexticTableCoefficient_36
  · exact orderFourSexticTableCoefficient_37
  · exact orderFourSexticTableCoefficient_38
  · exact orderFourSexticTableCoefficient_39
  · exact orderFourSexticTableCoefficient_40
  · exact orderFourSexticTableCoefficient_41
  · exact orderFourSexticTableCoefficient_42
  · exact orderFourSexticTableCoefficient_43
  · exact orderFourSexticTableCoefficient_44
  · exact orderFourSexticTableCoefficient_45
  · exact orderFourSexticTableCoefficient_46
  · exact orderFourSexticTableCoefficient_47
  · exact orderFourSexticTableCoefficient_48
  · exact orderFourSexticTableCoefficient_49
  · exact orderFourSexticTableCoefficient_50
  · exact orderFourSexticTableCoefficient_51
  · exact orderFourSexticTableCoefficient_52
  · exact orderFourSexticTableCoefficient_53
  · exact orderFourSexticTableCoefficient_54
  · exact orderFourSexticTableCoefficient_55
  · exact orderFourSexticTableCoefficient_56
  · exact orderFourSexticTableCoefficient_57
  · exact orderFourSexticTableCoefficient_58
  · exact orderFourSexticTableCoefficient_59
  · exact orderFourSexticTableCoefficient_60
  · exact orderFourSexticTableCoefficient_61
  · exact orderFourSexticTableCoefficient_62
  · exact orderFourSexticTableCoefficient_63
  · exact orderFourSexticTableCoefficient_64
  · exact orderFourSexticTableCoefficient_65
  · exact orderFourSexticTableCoefficient_66
  · exact orderFourSexticTableCoefficient_67
  · exact orderFourSexticTableCoefficient_68
  · exact orderFourSexticTableCoefficient_69
  · exact orderFourSexticTableCoefficient_70
  · exact orderFourSexticTableCoefficient_71
  · exact orderFourSexticTableCoefficient_72
  · exact orderFourSexticTableCoefficient_73
  · exact orderFourSexticTableCoefficient_74
  · exact orderFourSexticTableCoefficient_75
  · exact orderFourSexticTableCoefficient_76
  · exact orderFourSexticTableCoefficient_77
  · exact orderFourSexticTableCoefficient_78
  · exact orderFourSexticTableCoefficient_79
  · exact orderFourSexticTableCoefficient_80
  · exact orderFourSexticTableCoefficient_81
  · exact orderFourSexticTableCoefficient_82
  · exact orderFourSexticTableCoefficient_83
  · exact orderFourSexticTableCoefficient_84
  · exact orderFourSexticTableCoefficient_85
  · exact orderFourSexticTableCoefficient_86
  · exact orderFourSexticTableCoefficient_87
  · exact orderFourSexticTableCoefficient_88
  · exact orderFourSexticTableCoefficient_89
  · exact orderFourSexticTableCoefficient_90
  · exact orderFourSexticTableCoefficient_91
  · exact orderFourSexticTableCoefficient_92
  · exact orderFourSexticTableCoefficient_93
  · exact orderFourSexticTableCoefficient_94
  · exact orderFourSexticTableCoefficient_95
  · exact orderFourSexticTableCoefficient_96
  · exact orderFourSexticTableCoefficient_97
  · exact orderFourSexticTableCoefficient_98
  · exact orderFourSexticTableCoefficient_99
  · exact orderFourSexticTableCoefficient_100
  · exact orderFourSexticTableCoefficient_101
  · exact orderFourSexticTableCoefficient_102
  · exact orderFourSexticTableCoefficient_103
  · exact orderFourSexticTableCoefficient_104
  · exact orderFourSexticTableCoefficient_105
  · exact orderFourSexticTableCoefficient_106
  · exact orderFourSexticTableCoefficient_107
  · exact orderFourSexticTableCoefficient_108
  · exact orderFourSexticTableCoefficient_109
  · exact orderFourSexticTableCoefficient_110
  · exact orderFourSexticTableCoefficient_111
  · exact orderFourSexticTableCoefficient_112
  · exact orderFourSexticTableCoefficient_113
  · exact orderFourSexticTableCoefficient_114
  · exact orderFourSexticTableCoefficient_115
  · exact orderFourSexticTableCoefficient_116
  · exact orderFourSexticTableCoefficient_117
  · exact orderFourSexticTableCoefficient_118
  · exact orderFourSexticTableCoefficient_119
  · exact orderFourSexticTableCoefficient_120
  · exact orderFourSexticTableCoefficient_121
  · exact orderFourSexticTableCoefficient_122
  · exact orderFourSexticTableCoefficient_123
  · exact orderFourSexticTableCoefficient_124
  · exact orderFourSexticTableCoefficient_125
  · exact orderFourSexticTableCoefficient_126
  · exact orderFourSexticTableCoefficient_127
  · exact orderFourSexticTableCoefficient_128
  · exact orderFourSexticTableCoefficient_129
  · exact orderFourSexticTableCoefficient_130
  · exact orderFourSexticTableCoefficient_131
  · exact orderFourSexticTableCoefficient_132
  · exact orderFourSexticTableCoefficient_133
  · exact orderFourSexticTableCoefficient_134
  · exact orderFourSexticTableCoefficient_135
  · exact orderFourSexticTableCoefficient_136
  · exact orderFourSexticTableCoefficient_137
  · exact orderFourSexticTableCoefficient_138
  · exact orderFourSexticTableCoefficient_139
  · exact orderFourSexticTableCoefficient_140
  · exact orderFourSexticTableCoefficient_141
  · exact orderFourSexticTableCoefficient_142
  · exact orderFourSexticTableCoefficient_143
  · exact orderFourSexticTableCoefficient_144
  · exact orderFourSexticTableCoefficient_145
  · exact orderFourSexticTableCoefficient_146
  · exact orderFourSexticTableCoefficient_147
  · exact orderFourSexticTableCoefficient_148
  · exact orderFourSexticTableCoefficient_149
  · exact orderFourSexticTableCoefficient_150
  · exact orderFourSexticTableCoefficient_151
  · exact orderFourSexticTableCoefficient_152
  · exact orderFourSexticTableCoefficient_153
  · exact orderFourSexticTableCoefficient_154
  · exact orderFourSexticTableCoefficient_155
  · exact orderFourSexticTableCoefficient_156
  · exact orderFourSexticTableCoefficient_157
  · exact orderFourSexticTableCoefficient_158
  · exact orderFourSexticTableCoefficient_159
  · exact orderFourSexticTableCoefficient_160
  · exact orderFourSexticTableCoefficient_161
  · exact orderFourSexticTableCoefficient_162
  · exact orderFourSexticTableCoefficient_163
  · exact orderFourSexticTableCoefficient_164
  · exact orderFourSexticTableCoefficient_165
  · exact orderFourSexticTableCoefficient_166
  · exact orderFourSexticTableCoefficient_167
  · exact orderFourSexticTableCoefficient_168
  · exact orderFourSexticTableCoefficient_169
  · exact orderFourSexticTableCoefficient_170
  · exact orderFourSexticTableCoefficient_171
  · exact orderFourSexticTableCoefficient_172
  · exact orderFourSexticTableCoefficient_173
  · exact orderFourSexticTableCoefficient_174
  · exact orderFourSexticTableCoefficient_175
  · exact orderFourSexticTableCoefficient_176
  · exact orderFourSexticTableCoefficient_177
  · exact orderFourSexticTableCoefficient_178
  · exact orderFourSexticTableCoefficient_179
  · exact orderFourSexticTableCoefficient_180
  · exact orderFourSexticTableCoefficient_181
  · exact orderFourSexticTableCoefficient_182
  · exact orderFourSexticTableCoefficient_183
  · exact orderFourSexticTableCoefficient_184
  · exact orderFourSexticTableCoefficient_185
  · exact orderFourSexticTableCoefficient_186
  · exact orderFourSexticTableCoefficient_187
  · exact orderFourSexticTableCoefficient_188
  · exact orderFourSexticTableCoefficient_189
  · exact orderFourSexticTableCoefficient_190
  · exact orderFourSexticTableCoefficient_191
  · exact orderFourSexticTableCoefficient_192
  · exact orderFourSexticTableCoefficient_193
  · exact orderFourSexticTableCoefficient_194
  · exact orderFourSexticTableCoefficient_195
  · exact orderFourSexticTableCoefficient_196
  · exact orderFourSexticTableCoefficient_197
  · exact orderFourSexticTableCoefficient_198
  · exact orderFourSexticTableCoefficient_199
  · exact orderFourSexticTableCoefficient_200
  · exact orderFourSexticTableCoefficient_201
  · exact orderFourSexticTableCoefficient_202
  · exact orderFourSexticTableCoefficient_203
  · exact orderFourSexticTableCoefficient_204
  · exact orderFourSexticTableCoefficient_205
  · exact orderFourSexticTableCoefficient_206
  · exact orderFourSexticTableCoefficient_207
  · exact orderFourSexticTableCoefficient_208
  · exact orderFourSexticTableCoefficient_209
  · exact orderFourSexticTableCoefficient_210
  · exact orderFourSexticTableCoefficient_211
  · exact orderFourSexticTableCoefficient_212
  · exact orderFourSexticTableCoefficient_213
  · exact orderFourSexticTableCoefficient_214
  · exact orderFourSexticTableCoefficient_215
  · exact orderFourSexticTableCoefficient_216
  · exact orderFourSexticTableCoefficient_217
  · exact orderFourSexticTableCoefficient_218
  · exact orderFourSexticTableCoefficient_219
  · exact orderFourSexticTableCoefficient_220
  · exact orderFourSexticTableCoefficient_221
  · exact orderFourSexticTableCoefficient_222
  · exact orderFourSexticTableCoefficient_223

end DittertRybin
